### PR TITLE
Set infinite timeout for local commands

### PR DESCRIPTION
**Pull request by mbrodala**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

Very long running commands (e.g. DB import) can exceed even 5 minutes (see #955) thus switch to an infinite timeout for local commands.

### CODE REVIEW

**Comment by elfet** [comment]
Why not `runLocally('...', null)`?

**Comment by mbrodala** [comment]
@elfet Yes, for `runLocally()` this is possible but not with `run()` on a `localServer()`.

**Comment by elfet** [comment]
> not with run() on a localServer().
I think we need to fix API and allow to set timeout for this too.

```php
run('...', INF);
```

**Comment by mbrodala** [comment]
I'd be fine with that too. Notice that Symfony expects `null` for infinite timeouts, not `INF`.

**Comment by pluseg** [comment]
@elfet What do you think about `null` value for infinite timeouts? It blocks the PR.

**Comment by elfet** [comment]
Null is okay, but i like INF for verbosity. Also i'm thinking about changing `run` api in v5 to something like this: `run('...', $options)`. 
To becable pass timeouts, pty and other option for current run.

**Comment by mbrodala** [comment]
@elfet Sounds good. How to proceed on this PR? I can rebase to fix the conflicts if you think it makes sense to have this added.

A little more background: with custom tasks you can of course manually pass `null` to enable infinite timeout, however this is not possible with 3rd party tasks/recipes.

**Comment by elfet** [comment]
I will manually merge this pr later.

> however this is not possible with 3rd party tasks/recipes.
This is interesting point, we need found good API for it. What are problems to solve we want?

**Comment by mbrodala** [comment]
@elfet That won't be easy to fix. We can reconfigure tasks by now but not the function calls (e.g. `runLocally()`) within those tasks.

**Comment by elfet** [comment]
Done in #1092
```php
run('...', ['timeout' => null]);
runLocally('...', ['timeout' => null]);
```

**Comment by elfet** [comment]
Also i was thinking about renaming `runLocally` to `exec`.

**Comment by mbrodala** [comment]
@elfet The change you mentioned does not solve the issue mentioned here: I'd still need to copy the body of all tasks from 3rd party recipes to set the `timeout` option.

Thus please reconsider this PR.

**Comment by staabm** [comment]
> Also i was thinking about renaming runLocally to exec.

I like run and runLocally as they cleary communicate their purpose.
exec and run dont make a statement whether they run remotely or locally... this would harm readability

**Comment by elfet** [comment]
@mbrodala i see, maybe it's should be 3rd party issue? I like simplicity of options in _run_ function. For example, this is how i pass tty to git clone command: https://github.com/deployphp/deployer/pull/1092/commits/ace288978c633f621edbcd07c7512accf1cdf544#diff-b4ebd1b9bf76c38d2568949ec0c70c51

Of cause we can add some global param, but i don't like it for some reason.

**Comment by mbrodala** [comment]
You are probably right that the 3rd party recipes should offer options to customize the timeout.

**Pull request closed without merging**
