### PR TITLE
Composer - Try to use the global installation

### PR DESCRIPTION
**Pull request by KennedyTedesco**
Like suggested here: https://github.com/deployphp/deployer/issues/128

What you guys think? I have tested and worked fine.

### CODE REVIEW

**Comment by elfet** [comment]
I need some time to merge it without conflicts with my new common.php.

**Comment by tomzx** [comment]
Why download composer.phar to the `release_path` when you could/should download it to the `shared_path` instead?

Also, it'd be nice if we could not pollute commands with framework specific environment variables (such as `SYMFONY_ENV`).

**Comment by KennedyTedesco** [comment]
@tomzx I'm ok with that. :+1:

**Comment by elfet** [comment]
Done!

**Comment by KennedyTedesco** [comment]
Awesome! :smile:

**Pull request closed without merging**
