### PR TITLE
travis: PHP 7.0 nightly added

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by gordalina** [comment]
:+1:

**Comment by ZeeCoder** [comment]
:+1:

**Comment by elfet** [comment]
Maybe remove HHVM?

**Comment by ZeeCoder** [comment]
Reasons?

**Comment by elfet** [comment]
Does Deployer can be run on HHVM? 
Take a look to Travis-CI - all hhvm build are failing.

**Comment by ZeeCoder** [comment]
Well, it's hard to tell whether it would be easy to fix it or not.
But there's no harm in leaving it there, so I would leave it as it is for now, someone could always fix it. :)

**Comment by TomasVotruba** [comment]
@ZeeCoder I agree. After all, that's why it's in `allowed_failures` section.

**Comment by ZeeCoder** [comment]
exactly

**Pull request merged**
