### PR TITLE
Typehint functions file

### PR DESCRIPTION
**Pull request by tvbeek**
- [ ] Part of the improvement for #2187 
- [ ] New feature?
- [ ] BC breaks?
- [ ] Deprecations?
- [ ] Tests added?
- [x] Changelog updated?

As mentioned in #2187 the adding of type declarations can improve the quality of code. I added as far as I could in the src/functions.php file.

### CODE REVIEW

**Comment by antonmedv** [comment]
Please also include this file in phpcs check so we can be sure further improvements will not break it again.

**Comment by tvbeek** [comment]
Done and directly find some missing parts, thanks for pointing out. Do you want to have the commits squashed to one commit?

**Comment by antonmedv** [comment]
I’ll sqush it any way. Please, rebase. I can’t commit to you brunch.

**Comment by tvbeek** [comment]
> 
> 
> I’ll sqush it any way. Please, rebase. I can’t commit to you brunch.

I did a rebase.

**Pull request merged**
