### PR TITLE
Hotfix/v7.4.0: Fixes caddyfile and realpath errors in provision:website

### PR DESCRIPTION
**Pull request by midhunmonachan**
- [x] **Bug fix:** Fixes 2 bugs.  Related issue: [#3836](https://github.com/deployphp/deployer/issues/3836)

- [ ] ~~**New feature:** No features were added in this issue.~~

- [ ] ~~**BC breaks:** No backward compatibility breaks in this release.~~

- [ ] ~~**Tests added:** No new tests were added in this release.~~

- [ ] ~~**Docs added:** No new documentation was added in this release.~~

### CODE REVIEW

**Review by antonmedv — APPROVED** [review]

**Comment by Wordlesschunk** [comment]
I'm still getting this error with symfony even on 7.4, had to downgrade to         "deployer/deployer": "7.3.3",

**Comment by antonmedv** [comment]
Will release.

**Comment by calumshep** [comment]
Any news on this release? Also having to use 7.3.3 in the meantime.

**Comment by bendeckdavid** [comment]
There should be and var to allow to specify the caddyfile to use, if var is not set  then use the default file, I was using a custom caddyfile and this update was a problem for me.

**Comment by antonmedv** [comment]
This is a good idea. We can create a dir with all needed configuration go there. Like  `.dep/Caddyfile`

**Pull request merged**
