### PR TITLE
Fix Symfony recipe follow change of asset bundle

### PR DESCRIPTION
**Pull request by cmodijk**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | #720

This fixes the previous pull request #642

I also created a pull request on the docs for assetic users https://github.com/deployphp/docs/pull/65

### CODE REVIEW

**Comment by robfrawley** [comment]
FYI, this is already fixed in #688 though I don't know if they will ever merge it.

**Comment by cmodijk** [comment]
Wow #688 is kind of big but yeah i think it's better to merge that instead of this one. But maybe because of it's size its harder to merge.

**Comment by robfrawley** [comment]
@cmodijk You may want to just see if you can get this merged. I've been trying to get #688 merged for, quite literally, two months straight, now without a response from any Deployer member for a solid month. And this is despite the fact that deployer is quite literally broken when used with some versions of Symfony... Good luck!

**Comment by oanhnn** [comment]
@cmodijk Thank you! I make a symfony 3 project by command:
```shell
$ composer create-project symfony/framework-standard-edition sym3
```
After my project is created, i see:
```shell
$ bin/console 
Symfony version 3.1.3 - app/dev/debug

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -e, --env=ENV         The Environment name. [default: "dev"]
      --no-debug        Switches off debug mode.
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  help                                    Displays help for a command
  list                                    Lists commands
 assets
  assets:install                          Installs bundles web assets under a public web directory
 cache
  cache:clear                             Clears the cache
  cache:warmup                            Warms up an empty cache
 config
  config:dump-reference                   Dumps the default configuration for an extension
 debug
  debug:config                            Dumps the current configuration for an extension
  debug:container                         Displays current services for an application
  debug:event-dispatcher                  Displays configured listeners for an application
  debug:router                            Displays current routes for an application
  debug:swiftmailer                       Displays current mailers for an application
  debug:translation                       Displays translation messages information
  debug:twig                              Shows a list of twig functions, filters, globals and tests
 doctrine
  doctrine:cache:clear-collection-region  Clear a second-level cache collection region.
  doctrine:cache:clear-entity-region      Clear a second-level cache entity region.
  doctrine:cache:clear-metadata           Clears all metadata cache for an entity manager
  doctrine:cache:clear-query              Clears all query cache for an entity manager
  doctrine:cache:clear-query-region       Clear a second-level cache query region.
  doctrine:cache:clear-result             Clears result cache for an entity manager
  doctrine:database:create                Creates the configured database
  doctrine:database:drop                  Drops the configured database
  doctrine:ensure-production-settings     Verify that Doctrine is properly configured for a production environment.
  doctrine:generate:crud                  Generates a CRUD based on a Doctrine entity
  doctrine:generate:entities              Generates entity classes and method stubs from your mapping information
  doctrine:generate:entity                Generates a new Doctrine entity inside a bundle
  doctrine:generate:form                  Generates a form type class based on a Doctrine entity
  doctrine:mapping:convert                Convert mapping information between supported formats.
  doctrine:mapping:import                 Imports mapping information from an existing database
  doctrine:mapping:info                   
  doctrine:query:dql                      Executes arbitrary DQL directly from the command line.
  doctrine:query:sql                      Executes arbitrary SQL directly from the command line.
  doctrine:schema:create                  Executes (or dumps) the SQL needed to generate the database schema
  doctrine:schema:drop                    Executes (or dumps) the SQL needed to drop the current database schema
  doctrine:schema:update                  Executes (or dumps) the SQL needed to update the database schema to match the current mapping metadata.
  doctrine:schema:validate                Validate the mapping files.
 generate
  generate:bundle                         Generates a bundle
  generate:command                        Generates a console command
  generate:controller                     Generates a controller
  generate:doctrine:crud                  Generates a CRUD based on a Doctrine entity
  generate:doctrine:entities              Generates entity classes and method stubs from your mapping information
  generate:doctrine:entity                Generates a new Doctrine entity inside a bundle
  generate:doctrine:form                  Generates a form type class based on a Doctrine entity
 lint
  lint:twig                               Lints a template and outputs encountered errors
  lint:yaml                               Lints a file and outputs encountered errors
 orm
  orm:convert:mapping                     Convert mapping information between supported formats.
 router
  router:match                            Helps debug routes by simulating a path info match
 security
  security:check                          Checks security issues in your project dependencies
  security:encode-password                Encodes a password.
 server
  server:run                              Runs PHP built-in web server
  server:start                            Starts PHP built-in web server in the background
  server:status                           Outputs the status of the built-in web server for the given address
  server:stop                             Stops PHP's built-in web server that was started with the server:start command
 swiftmailer
  swiftmailer:debug                       Displays current mailers for an application
  swiftmailer:email:send                  Send simple email message
  swiftmailer:spool:send                  Sends emails from the spool
 translation
  translation:update                      Updates the translation file
```
So that, should we remove command?
```php
run('{{bin/php}} {{release_path}}/' . trim(get('bin_dir'), '/') . '/console assets:install --env={{env}} --no-debug {{release_path}}/web');
```

**Comment by robfrawley** [comment]
> So that, should we remove command?

@oanhnn No, you should not.

You should merge #688, which implements the proper behavior of running `assets:install` for **both** symfony 2 and 3 (versus only version 3 currently), and then requiring `assetic:dump` be enabled via the boolean config (instead of running for default in symfony 2 and overridden by assets:install in symfony 3), as it may or may not exist in any given install for all symfony versions.

**Comment by oanhnn** [comment]
Yes. Thank @robfrawley . I will process with your PR

**Comment by elfet** [comment]
I'm going to close this PR right now. All BC go to 4.x.

**Pull request closed without merging**
