### PR TITLE
[httpie] Delete Content-Length

### PR DESCRIPTION
**Pull request by joanhey**
- [ ] Bug fix #…?
- [ ] New feature?
- [ ] BC breaks?
- [ ] Tests added?
- [ ] Docs added?

      Please, regenerate docs by running next command:
      $ php bin/docgen

Curl add it automatically. ~And also change it if it isn't correct~.
If we add the `Content-Length` will replace the internal one created by Curl.

### CODE REVIEW

**Comment by antonmedv** [comment]
But why?

**Comment by joanhey** [comment]
Curl receive the body via 
`curl_setopt($ch, CURLOPT_POSTFIELDS, $this->body);`

And it add the `Content-Length`.
If we set an incorrect `Content-Length` will be a malformed request.

**Comment by joanhey** [comment]
But the important thing is that Curl add it.
So less code in PHP.

**Comment by antonmedv** [comment]
I see. didn't know about curl_setopt($ch, CURLOPT_POSTFIELDS, $this->body);

**Comment by joanhey** [comment]
Another PR will change this line
`curl_setopt($ch, CURLOPT_POSTFIELDS, $this->body);`

to:
```
if($this->body) {
 curl_setopt($ch, CURLOPT_POSTFIELDS, $this->body);
}
```
Now when is a GET add an extra header that is not necessary.

**Comment by joanhey** [comment]
Joined in #3098

**Pull request closed without merging**
