### PR TITLE
Implement SSH Agent Forwarding Feature

### PR DESCRIPTION
**Pull request by oanhnn**
This pull request includes:
- Implement [SSH Agent Forwarding Feature #134 ](https://github.com/deployphp/deployer/issues/134)
- Unit test for `Builder::forwardAgent()` method   

How to use?
```php
<?php 
// file: deployer.php
server('deployer', 'domain.com', 22)
    ->forwardAgent();

```

### CODE REVIEW

**Comment by elfet** [comment]
Cool! :gem: :gem: :gem: :beers:

**Comment by elfet** [comment]
Is it working correctly? Can you show example of usage? And, please fix merge conflicts :wink:

**Comment by oanhnn** [comment]
I test and working good with my system.
Here is my `deployer.php` file
```php
<?php
require 'recipe/common.php';

server('dev', 'domain.com', 22)
    ->user('dev')
    ->forwardAgent()
    ;

set('repository', 'git@github.com:oanhnn/slim-skeleton.git');
set('deploy_path', '/var/www/apps/slim');
env('deploy_path', get('deploy_path'));

task('deploy:start', function() {
    run("if [ ! -d {deploy_path} ]; then mkdir -p {deploy_path}; fi");
});

/**
 * Success message
 */
task('deploy:end', function () {
    $host = config()->getHost();
    writeln("<info>Successfully deployed on</info> <fg=cyan>$host</fg=cyan>");
});

/**
 * Main task
 */
task('deploy', [
    'deploy:start',
    'deploy:prepare',
    'deploy:update_code',
    'deploy:vendors',
    'deploy:symlink',
    'cleanup',
    'deploy:end'
])->desc('Deploy your project');
```

Please allow forward agent function with ssh configure follow post https://developer.github.com/guides/using-ssh-agent-forwarding/

**Comment by elfet** [comment]
Cool! Thanks!

**Comment by oanhnn** [comment]
I think you should change function `server()` in `functions.php` for always using `PhpSecLib` until SSH2 extension support this feature

**Comment by elfet** [comment]
Yes, i think so. Create settings with PhpSecLib by default.

**Comment by tomzx** [comment]
@oanhnn, how is it that you have agent forwarding in `phpseclib` while it appears that the issue is not yet merged into `master` on their side? Have you manually patched up your deployer installation with the current PR  from there? If so, it means this PR is incomplete and will not work.

**Comment by elfet** [comment]
@oanhnn ping

**Comment by oanhnn** [comment]
Sorry, I am vacationing Tet holiday.
I have problem with forward agent when change from using `capistrano` to using `deployer`.
I was waiting and follow this feature, but i need this to deploy my project (from bitbucket.org) and can not wait longer. I was search solution and found [issue 4235](https://github.com/laravel/framework/issues/4235) on Laravel Framework.
I was try implement this feature and success with my system.
I think `phpseclib` was implement this feature but didn't create document, and not yet merged.

**Pull request merged**
