### PR TITLE
Support Symfony 6

### PR DESCRIPTION
**Pull request by trsteel88**

### CODE REVIEW

**Comment by antonmedv** [comment]
Please use deployer/dist.

**Comment by trsteel88** [comment]
Not sure what that means @antonmedv?

**Comment by Schrank** [comment]
deployer/dist is a repository right beside this one which contains the phar files.

https://deployer.org/download
https://github.com/deployphp/distribution

**Comment by trsteel88** [comment]
Sorry, I don't understand what you're asking me to do. Looking at https://github.com/deployphp/distribution it's pretty much blank.

Do you have any instructions on how to contribute to this repository?

**Comment by trsteel88** [comment]
@antonmedv, there's quite a few PR's where you ask the PR owner to use deployer/dist but I can't see any explanation anywhere on what this means or how to contribute. If you can provide more info that would be great.

**Comment by antonmedv** [comment]
Deployer/dist is drop in replacement. It has phar files in it.

**Comment by trsteel88** [comment]
@antonmedv I still don't understand how to contribute the change.

**Comment by antonmedv** [comment]
Dist doesn’t have composer deps. All deps was bundled in a phar.

**Comment by antonmedv** [comment]
Take a look at a tag https://github.com/deployphp/distribution/tree/v7.0.0-rc.4

**Comment by trsteel88** [comment]
I've had a look - I have no idea what this repository is. I just want to allow Symfony 6 within this repositories composer.json.

dist doesn't have any composer deps so I can't update the Symfony requirement in there.

**Comment by antonmedv** [comment]
Do you know what is phar?

**Comment by trsteel88** [comment]
Sorry it just clicked, you're saying to include the dist version in my project rather than relying on this repository. 

I thought you were asking me to submit a PR under a different repo.

**Comment by Schrank** [comment]
Sometimes we are not the best in explaining intentions.

yes! 

By only using the phar file from dist, you get rid of all dependencies and therefore off your problem. Our recommendation: NEVER use the same composer.json for your running software as for your testing, building, deployment, etc.
Because you don’t want to poison your dependencies with the dependencies of phpunit, deployer or phpstan.

hope that helps and good luck!

and thanks for your patience and endurance by asking 👍

**Pull request closed without merging**
