### PR TITLE
Fix inventory method

### PR DESCRIPTION
**Pull request by fagai**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

I fixed it because I can not do the operation written in the documentaion.
https://deployer.org/docs/hosts#multiple-hosts

```php
inventory('hosts.yml') // ← not Proxy return!
    ->roles('app')
    ...
```

### CODE REVIEW

**Comment by antonmedv** [comment]
Please, update CHANGELOG.md

**Comment by fagai** [comment]
updated.

**Comment by antonmedv** [comment]
Now tests are falling. :) Add reference too, please.

**Comment by fagai** [comment]
Sorry, added reference.

**Comment by antonmedv** [comment]
I've added more info about how to add lines in CHANGELOG.md

**Comment by GitHub30** [comment]
thx

**Pull request merged**
