### PR TITLE
Remove composer lock file

### PR DESCRIPTION
**Pull request by bestlong**
Not suggest include composer.lock

| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

### CODE REVIEW

**Comment by antonmedv** [comment]
composer.lock used for phar creation. Why to remove?

**Comment by bestlong** [comment]
@antonmedv composer.lock will created when run `composer install`.

**Comment by antonmedv** [comment]
I know, This file lock specified versions.

**Comment by adriandmitroca** [comment]
.lock files should always be in every repository, without any exceptions really.

**Comment by antonmedv** [comment]
@adriandmitroca not for libraries :) 
But in case of phar creation, it's ok.

**Comment by adriandmitroca** [comment]
@antonmedv 

After some thinking you are definitely right. Thanks for putting me on right direction! <3

**Comment by bestlong** [comment]
@antonmedv please ref https://travis-ci.org/laradock/laradock/jobs/342684374
have any suggest?

**Comment by bestlong** [comment]
switch to use Phar version.

**Pull request closed without merging**
