### PR TITLE
Update shopware.php

### PR DESCRIPTION
**Pull request by Webmasterei**
Improved Versions

- [ ] Bug fix #…?
- [ ] New feature?
- [ ] BC breaks?
- [ ] Deprecations?
- [ ] Tests added?
- [ ] Changelog updated?

      Please, update CHANGELOG.md by running next command:
      $ php bin/changelog

### CODE REVIEW

**Comment by Schrank** [comment]
Hi @Webmasterei, thanks for your Pull Request! May you tell me, what you did?

**Comment by Webmasterei** [comment]
Hi Fabian, 
I almost completely refactored it and added some missing functinalities. Working smooth now.

**Comment by Schrank** [comment]
Can you elaborate on that?

- What problems did you have and how did you fix them?
- What functionality was missing?

It is really hard for me to read the diff without context.
Thank you very much!

**Comment by antonmedv** [comment]
Ping @Webmasterei

**Comment by Webmasterei** [comment]
@Schrank it has been rewritten and completed in many parts. So wide parts of logic were constructed new and other processes have been added. That is, why diff doesn't work well on that change.

**Comment by antonmedv** [comment]
So can I close this PR? Or some parts still need to be merged?

**Comment by Webmasterei** [comment]
I thinks, thats all

Am Mo., 8. März 2021 um 08:54 Uhr schrieb Anton Medvedev <
notifications@github.com>:

**Pull request closed without merging**
