### PR TITLE
Added the laravel default folder storage/framework/cache to writable folders array

### PR DESCRIPTION
**Pull request by juliangarcess**
- [ ] Bug fix #…?
- [X] New feature?
- [ ] BC breaks?
- [ ] Tests added?
- [X] Docs added?

      Please, regenerate docs by running next command:
      $ php bin/docgen

### CODE REVIEW

**Comment by peterjaap** [comment]
In what situation would omitting this cause an issue? I've never seen this being a problem and I don't think adding this is necessary so I'd love to hear why you think this is needed in the general recipe instead of just for your installation?

**Comment by juliangarcess** [comment]
As storage/framework/cache/data is a default folder of fresh laravel instalation is not affected by umask cause it comes directly from git repository, I think that this folder must be specifically mentioned in writable_dirs array.

In my personal experience I have problems with the recipe until I added that folder to writable array.

**Comment by peterjaap** [comment]
Curious to hear from more people having problems with this. We've been using this recipe for years and haven't run into this issue yet.

**Comment by juliangarcess** [comment]
what`s the problem with this PR? why it is not merged??

**Comment by Schrank** [comment]
Because @peterjaap doesn't have this issue and the question is, is this a generic problem or one of your deployment

**Comment by peterjaap** [comment]
I think the problem lies here, from your comment;

> not affected by umask cause it comes directly from git repository

This folder shouldn't be in any git repository, since it's a cache folder. So I'd advise you to remove it from your git by doing `git remote --cached storage/framework/cache`. That way, the webserver will create the folder and you won't run into problems.

**Comment by juliangarcess** [comment]
If you install a fresh laravel aplication that folder came by default, then it must be mentioned on the recipe

**Pull request merged**
