### PR TITLE
Fixes upload / download with optional rsync ssh option #1227

### PR DESCRIPTION
**Pull request by dirx**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | #1227

### CODE REVIEW

**Comment by ceesvanegmond** [comment]
@antonmedv Tag please :-)

**Comment by antonmedv** [comment]
Okay)

**Comment by ceesvanegmond** [comment]
@antonmedv 5.0.2?

**Comment by antonmedv** [comment]
Sorry for delay)

**Pull request merged**
