### PR TITLE
Replace phar build script with box-project/box2 build tool.

### PR DESCRIPTION
**Pull request by tomzx**
Adds a box.json file that should replace the configuration used in the build file.
Removes the old build file (since it is replaced by the configuration file).

File size goes from 3 MB to ~485 KB.

Reference: #190

### CODE REVIEW

**Comment by elfet** [comment]
What if i add `$phar->compressFiles(Phar::GZ);` to my build script? 
Now deployer.org site uses my `build` script, so we need to refactoring them too.
What is the benefit ща migration to `box2`?

**Comment by elfet** [comment]
New size of `deployer.phar` 825KB now.

I think we need to reduce number of dependencies.

**Comment by gordalina** [comment]
Nice job @tomzx 
Box really makes it simple to package an app. 
 
I would like to add that enabling gzip compression could lead to php installations (without gzip extension enable), to fail loading the phar. Also Composer [had an issue](https://github.com/composer/composer/blob/1.0.0-alpha9/src/Composer/Compiler.php#L131) with this before.

Regarding the size of the phar, I guess we (developers) have reasonably fast bandwidth to transfer a larger file, thus making it less relevant.

**Comment by tomzx** [comment]
@elfet Why do you prefer your own build script to using a library that is used/tested by many? What would make you change your mind?

**Comment by elfet** [comment]
Hmmm, i'll think about it :)

**Comment by gpupo** [comment]
I agree with @tomzx. Nice job

**Comment by elfet** [comment]
Box awesome project, but i do not what to touch what's already good working. 
Also i do not see any cons of this.

**Pull request closed without merging**
