### PR TITLE
Fix temporary workaround in Shopware recipe

### PR DESCRIPTION
**Pull request by phizab**
If I'm right the workaround is no longer needed, since it was fixed in Shopware 6.4.6.0: https://issues.shopware.com/issues/NEXT-17720. Can anyone confirm this please?

Can anyone confirm this please?

### CODE REVIEW

**Comment by phizab** [comment]
@UlrichThomasGabor You mentioned this workaround in https://github.com/deployphp/deployer/issues/2710#issuecomment-954821426. Can you confirm that it got fixed in 6.4.6.0?

**Comment by Schrank** [comment]
Thanks for the PR!

Can we please be very careful with this? If I understand it correctly, it kills deployment for SW < 6.4.6

**Comment by Schrank** [comment]
Hey @phizab 👋👋👋

**Comment by UlrichThomasGabor** [comment]
Was fixed in 6.4.6
https://github.com/shopware/platform/commit/01c8ff86c7d8d3bee1888a26c24c9dc9b4529cbc
https://issues.shopware.com/issues/NEXT-17720

I would not remove it though, because the potential downside of replacing something wrong is basically non-existent, but for old version it will just break without the command.

**Comment by UlrichThomasGabor** [comment]
> Was fixed in 6.4.6 [shopware/platform@01c8ff8](https://github.com/shopware/platform/commit/01c8ff86c7d8d3bee1888a26c24c9dc9b4529cbc) https://issues.shopware.com/issues/NEXT-17720

I would add those thinks as comments though.

**Comment by phizab** [comment]
I just followed the discussion in #2710 and thought the way there was to update the recipe along shopware updates and to get a clean recipe in Deployer 7. But it's okay for me to keep the workaround for a certain time.

**Comment by phizab** [comment]
Hey @Schrank 😉

**Comment by Schrank** [comment]
> I just followed the discussion in #2710 and thought the way there was to update the recipe along shopware updates and to get a clean recipe in Deployer 7. But it's okay for me to keep the workaround for a certain time.

You know what: You are right. We already decided to have two recipes, so let us have one for the latest version we can achieve with a recipe 👍

**Comment by UlrichThomasGabor** [comment]
Well, I think there is a difference between working around a bug, which has no down-sides of being left in place, and a recipe being unable to be used with current versions because it just does not fit the current deployment process anymore.

But I don't care that much, because this can be easily fixed by extending the recipe. Feel free if a workaround causing no harm annoys you ;)

**Comment by phizab** [comment]
It doesn't bother me, too. I was only struggling with the path used in the sed command, which doesn't fit to the path in my environment (see #2754) and I saw that the bug the workaround is for got fixed in Shopware. So I thought about discussing to remove it, but don't want to break any deployments with this change.

But I still think the path "/var/www/htdocs" should be customizable, shouldn't it? Isn't it {{deploy_path}} or something like this?

@UlrichThomasGabor I reverted the commit and changed the comment. What do you think?

@Schrank Since there is only this recipe yet I and I don't want to break anything I would keep it for the moment :shrug:

**Comment by Schrank** [comment]
I would love to create the second, but...

**Comment by UlrichThomasGabor** [comment]
> But I still think the path "/var/www/htdocs" should be customizable, shouldn't it? Isn't it {{deploy_path}} or something like this?

Yes, this should be replaced, but I was too lazy and annoyed by the escaping to make it right.... feel free ;)

**Comment by peterjaap** [comment]
I wanted to fix this but I don't have an example file to test the `sed` command against since I've upgraded my Shopware installs. Could someone supply me with one (with absolute paths)?

@phizab in the meantime, could you update the PR to append `|| true` ? That way, the `sed` command will fail silently for >= 6.4.6 installs.

So;

```
runLocally('sed -i "" -E \'s/\\\\\/var\\\\\/www\\\\\/htdocs\\\\\/releases\\\\\/[0-9]+\\\\\///g\' files/theme-config/* || true');
```

**Comment by phizab** [comment]
@peterjaap Thanks for taking over and the hotfix. I've updated the `sed` command and the docs. Unfortunately I upgraded Shopware recently, too, so I don't have an example file.

**Comment by peterjaap** [comment]
@antonmedv I'm fine with merging this for now.

Let's keep https://github.com/deployphp/deployer/issues/2754 open so somebody (me?) can fix the hardcoded path. But I'd need an example file for that. @Schrank ?

**Comment by UlrichThomasGabor** [comment]
I can take a look at that hard-coded path when I clean up my recipe here and rebase it onto the Deployer recipe. But will take a few weeks I guess, sorry

**Comment by peterjaap** [comment]
@UlrichThomasGabor I will fix it, all I need is an example file with absolute paths!

**Comment by UlrichThomasGabor** [comment]
It seems I don't have one anymore.

But I guess you can easily break a shopware instance by removing [this single line](https://github.com/shopware/platform/blob/01c8ff86c7d8d3bee1888a26c24c9dc9b4529cbc/src/Storefront/Theme/ThemeFileResolver.php#L74), clear the cache `rm -Rf var/cache/*` and then run `./bin/console theme:dump` and look into `files/theme-config/*`.

Or just edit the JSON file manually:
```javascript
"storefrontEntryFilepath":"custom\/plugins\/SwagExample\/src\/Resources\/app\/storefront\/src\/main.js"
```
was something like
```javascript
"storefrontEntryFilepath":"\/var\/www\/releases\/105\/custom\/plugins\/SwagExample\/src\/Resources\/app\/storefront\/src\/main.js"
```

Because the search string is that specific, I did not bother with parsing the JSON, but just replaced every occurrence of the string.

**Comment by Schrank** [comment]
```
        "storefront": {
            "path": "Resources\/app\/storefront\/src",
            "entryFilePath": "Resources\/app\/storefront\/src\/main.js",
            "webpack": null,
            "styleFiles": [
                "\/var\/www\/customer.stage.winkelwagen.de\/releases\/20211124115627\/vendor\/shopware\/storefront\/Resources\/app\/storefront\/src\/scss\/base.scss",
                "\/var\/www\/customer.stage.winkelwagen.de\/releases\/20211124115627\/vendor\/shopware\/storefront\/Resources\/app\/storefront\/src\/scss\/skin\/shopware\/_base.scss",
                "@Plugins"
            ]
        }
    },
```

**Comment by peterjaap** [comment]
I continued working on this here; https://github.com/deployphp/deployer/issues/2754#issuecomment-982950659

**Pull request merged**
