### PR TITLE
Update shopware6.php

### PR DESCRIPTION
**Pull request by Schrank**
I'm not sure wether this is interesting for your @peterjaap I hacked a script with the horrible table output to install, upgrade and activate all plugins

### CODE REVIEW

**Comment by peterjaap** [comment]
I built the exact same thing but my approach was a bit less hacky; I created [a PR at the shopware/platform repo](https://github.com/shopware/platform/pull/1232) that adds a `--format=json` flag to the plugin:list command.

I then use this to install & activate plugins on deploy, like this;

```
task('sw:plugin:activate:all', function(){
    task('sw:plugin:refresh');
    $json = run('cd {{release_path}} && bin/console plugin:list --format=json');
    $pluginList = json_decode($json, true);
    foreach ($pluginList as $plugin) {
        run('cd {{release_path}} && bin/console plugin:install --activate ' . $plugin[0]);
    }
});
```

Until it has been merged, I use a composer patch to apply the PR in my project.

So I didn't add it in the recipe yet, since it depends on code that isn't in the core yet.

**Comment by Schrank** [comment]
Brilliant idea! 🙈

https://issues.shopware.com/issues/NEXT-10723

**Comment by peterjaap** [comment]
@Schrank Ugh, the dreaded mostly German Shopware Issuetracker :( They should really kill that and just move it to Github, like any mature company.

**Comment by Schrank** [comment]
Not gonna happen 🤷‍♂️

**Comment by antonmedv** [comment]
So this PR ok to merge? Maybe someone would like to join as maintainer for the recipe?

**Comment by Schrank** [comment]
The solution by @peterjaap doesn't work until the PR is merged, so I think, merging it and cleaning it up, once the PR is merged is a way to go. And I'm happy to join (pretty sure @peterjaap  as well 😅 )

**Comment by antonmedv** [comment]
Sounds good!

**Comment by antonmedv** [comment]
Let’s chat little about it t.me/antonmedv

**Pull request merged**
