### PR TITLE
Update composer it self before updating vendors

### PR DESCRIPTION
**Pull request by ihsanudin**
Update composer it self before updating vendors

### CODE REVIEW

**Comment by elfet** [comment]
Are you sure to do it automatically? Maybe add some options?

**Comment by ihsanudin** [comment]
Yes, I think automatic updates whenever deploy is better. But config/options is not bad

**Comment by ihsanudin** [comment]
@elfet : this PR is same as download new composer.phar but it is downloading update

**Comment by oanhnn** [comment]
@ihsanudin In a lot of cases, users installed `composer` global with root user ( using sudo ), this PR will be error. I think the update `composer` is customized by individual.

**Comment by ihsanudin** [comment]
@oanhnn : you are right, ok may be better to check if use sudo, try to update `composer` automatically

**Comment by elfet** [comment]
`sudo` isn’t solution.

**Comment by oanhnn** [comment]
@ihsanudin Using `sudo` to update `composer` and make writable dirs are two problem different. You can't using same config. I think **the updating composer task have do manually**.
@elfet I think this PR should be closed.

**Comment by elfet** [comment]
Agree.

**Pull request closed without merging**
