### PR TITLE
Fix return types for fluent interface

### PR DESCRIPTION
**Pull request by lstrojny**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | Kinda
| Deprecations? | No
| Fixed tickets | N/A

### CODE REVIEW

**Comment by antonmedv** [comment]
What is it?

**Comment by lstrojny** [comment]
Are you asking what the PR contains? It fixes all fluent interfaces in the Host class to return self, instead of `@return $this` (which is wrong) or `Host` as a type hint (which can be lifted to be `self`).

**Comment by antonmedv** [comment]
And why BC break kinda?

**Comment by lstrojny** [comment]
Since `Host` is a non-final class, somebody could have extended Host and overridden a method that doesn't have a return type hint as of now. If we now add one, this could render declaration could become incompatible.

```
<?php
class Host
{
    public function methodReturningSomething()
    {}
}

class MyHost extends Host {
    public function methodReturningSomething(): MyHost
    {}
}
```

This works just fine. This will trigger a fatal error though:
```
<?php
class Host
{
    public function methodReturningSomething(): Host
    {}
}

class MyHost extends Host {
    public function methodReturningSomething(): MyHost
    {}
}
```

```
Fatal error: Declaration of MyHost::methodReturningSomething(): MyHost must be compatible with Host::methodReturningSomething()
```

**Comment by antonmedv** [comment]
I see, I think it's okay.

**Pull request merged**
