### PR TITLE
[task deploy:shared] Copy shared files/directory

### PR DESCRIPTION
**Pull request by dirkluijk**
See https://github.com/deployphp/deployer/issues/152

Summary:
* Copies shared directories from source recursively, without overwriting existing files
* Copies shared files from source, if the file doesn't exists an empty one is created

### CODE REVIEW

**Comment by oanhnn** [comment]
@dirkluijk , I think you should implement this feature as optional, copy or not.

**Comment by gordalina** [comment]
I agree with @oanhnn, there should be an option to enable this. Current method should be the default.

**Comment by dirkluijk** [comment]
Hm, flexibility is great, but I couldn't imagine a situation where you want empty files/directories if the files and directories already exist in source control? Because that would still be possible of they don't exist.

Of course I could make it optional, but I can't figure out how. It seems not possible to add additional options to a ``TaskCommand`` generated by ``task``. And separate it from the current task is also not an option, because this currently removes to existing files/directories before creating the symlinks.

**Comment by oanhnn** [comment]
Dear @dirkluijk ,

Source code (checkout from git) is deployed on stages. So that, configure files (`shared_files`, `shared_dirs`) are modified when deploy to a special stage.
When re-deploy on stage, if copy original configure files, you have modify it again. Are you want this?
I think we should generate configure files in first deploy and re-generate it when stage have change. 
And we need a task to generate configure files instead of copy it from source code.

You can implement this feature as option, using env vars. Eg `env('copy_original_shared')`. 

```php
env('copy_original_shared', false);

task('deploy:shared', function(){
    // ...
    if (env('copy_original_shared')) {
        // copy original shared files and dirs
    }
    // ...
});
```

**Comment by dirkluijk** [comment]
@oanhnn: the files are only copied the first time, the second time the files will not be overwritten thanks to the ``-n`` flag. I think that's the desired behaviour.

**Comment by elfet** [comment]
Can you make these changes to `master` branch? Not more features will be implemented in 2.x branch.

**Pull request closed without merging**
