### PR TITLE
Updated to PHP SSH 1.1.1

### PR DESCRIPTION
**Pull request by gquemener**
This version improves command execution error detection

### CODE REVIEW

**Comment by gquemener** [comment]
See https://github.com/Herzult/php-ssh/pull/44

**Comment by gquemener** [comment]
Hello @elfet,
Could you review this one please?

Main problem with php-ssh@1.1.0 is that it relies on stderr to check if executed command failed or not BUT since a few weeks, composer writes a lot of things to stderr that are not errors (see my previous comment for the reasons).

Basically, all deployer users that uses composer during deployment (so a good majority of its users) will get a RuntimeException during composer install step.

I've fixed the problem on php-ssh, all you have to do now is to update deployer, and then we can share a :beers:

**Comment by Djeg** [comment]
:+1:

**Comment by Shivoham** [comment]
:+1:

**Comment by wysow** [comment]
:+1:

**Comment by elfet** [comment]
Great! Sorry about delay. :beer:

**Pull request merged**
