### PR TITLE
Added support for ntfy.sh notifications, contrib/ntfy

### PR DESCRIPTION
**Pull request by HereticPilgrim**
- [ ] Bug fix #…?
- [x] New feature: added support for ntfy.sh notifications
- [ ] BC breaks?
- [ ] Tests added? --> No. If you can give me some pointers on how to do it, I will gladly add them.
- [x] Docs added?

      Please, regenerate docs by running next command:
      $ php bin/docgen

### CODE REVIEW

**Comment by HereticPilgrim** [comment]
All other contrib recipes use `{{target}}` for the default notification.
This results in notifications like:
```_HereticPilgrim_ deploying `main` to *main*```

I used `{{hostname}}` as it's more intuitive for me, resulting in:
```_HereticPilgrim_ deploying `main` to *example.com*```

If you want, I can standardize on `{{target}}`

**Comment by antonmedv** [comment]
Lets fix info messages)

**Comment by HereticPilgrim** [comment]
Can you elaborate on what you mean by "fix"?
Would you prefer `{{hostname}}` in the other contrib-recipes or should I change my version to include `{{target}}`?

**Comment by antonmedv** [comment]
Can you show an example of what do you think?

**Pull request merged**
