### PR TITLE
Local process: add option to configure timeout with process_timeout

### PR DESCRIPTION
**Pull request by davidkudera**
Unfortunately there is no way to change process timeout for commands running on local server. Method `runLocally` has that option.

### CODE REVIEW

**Comment by oanhnn** [comment]
I think all servers (local or remote) should support timeout link pull request #328 
And not using env var.

**Comment by elfet** [comment]
Agree with @oanhnn.

**Comment by davidkudera** [comment]
Yep, you are of course right. Sorry I didn't noticed that pull request :wink:

**Comment by elfet** [comment]
But that PR is hang out. May be you can fork this PR, fix suggestion and create your own PR baser on that? @davidkudera?

**Comment by davidkudera** [comment]
@elfet I'm thinking about it too, so I'll probably do that, because I really need that

**Comment by elfet** [comment]
Cool!

**Pull request closed without merging**
