### PR TITLE
[Magento] add task to set permissions on files and directories to prevent all access to everyone

### PR DESCRIPTION
**Pull request by lohoy**
When I create artifact and deliver the package on server, the zip artifact keep permissions of locale directory.

I add task to set good permissions before zip artifact to set 644 permissions on files (754 on executable files in bin directory) and 755 permissions on directories.

### CODE REVIEW

**Comment by antonmedv** [comment]
I think this is not very common problem.

**Comment by peterjaap** [comment]
Agreed

**Comment by PierreGauthier** [comment]
@antonmedv I think you should reconsider this fix
Because the artifact file permission should not depend on the permissions of the system that builds the artifact.
Without this fix, if you build the artifact on a CI like github workflow or gitlab ci, you will deploy file with 777 permissions on the server, which is not very secure.

**Comment by peterjaap** [comment]
@PierreGauthier the file permission should not depend on the permissions of the system that builds the artifact, that is true.

The file permission should also not depend on a task that is configured in said system.

The file permissions however *should* depend on its file permission configuration in the repository, which Git supports.

**Pull request closed without merging**
