### PR TITLE
Create command to show current deployed versions

### PR DESCRIPTION
**Pull request by barryvdh**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes
| BC breaks?    | No
| Deprecations? |  No
| Fixed tickets | N/A 

This checks the current revision on each host and shows them. This makes it easy to see which versions are actually deployed already.

Example:

```
+----------------------+------------------+------------------+---------+
| Host                 | Author           | Date             | Commit  |
+----------------------+------------------+------------------+---------+
| test.mydomain.com    | Mathieu          | 2018-02-12 12:16 | 27e4ebb |
|                      |-----------------------------------------------|
|                      | Import db fix                                 |
|----------------------------------------------------------------------|
| demo.mydomain.com    | Mathieu          | 2018-02-12 12:16 | 27e4ebb |
|                      |-----------------------------------------------|
|                      | Import db fix                                 |
|----------------------------------------------------------------------|
| admin.mydomain.com   | Barry vd. Heuvel | 2018-02-05 17:04 | 60eb5c8 |
|                      |-----------------------------------------------|
|                      | Remove debug                                  |
+----------------------+------------------+------------------+---------+
```

### CODE REVIEW

**Comment by antonmedv** [comment]
This is really nice feature. But actually I'm working on same just in the moment. Soon will be release. Can you create separate repo with your recipe? 

PS I'll fix recipe require for phar ;)

**Comment by gzumba** [comment]
I would love to see the tag (if any) here too, if possible. And the branch. I always deploy by branch or tag, so it would be way more helpful than the commit hash alone.

**Comment by barryvdh** [comment]
> This is really nice feature. But actually I'm working on same just in the moment. Soon will be release. Can you create separate repo with your recipe?

If your version will include similar functionality, I'll just wait for that :)

Mine was based on this gist, so could include more stuff. https://gist.github.com/varemenos/e95c2e098e657c7688fd 
Not sure of tag/branch are possible with git rev though.

**Comment by gzumba** [comment]
Tag can be fetched with: git describe --tags
Branch can be fetched with: git rev-parse --abbrev-ref HEAD

I would be surprised if there were no packages that would implement these sort of git tooling in packagist already.

**Pull request closed without merging**
