### PR TITLE
Enhancement: Add deploy:is-unlocked

### PR DESCRIPTION
**Pull request by localheinz**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | #2150 

This PR

* [x] adds a command that allows to check if a deploy is locked

### CODE REVIEW

**Comment by antonmedv** [comment]
Thank you! Awesome to see tests.

**Comment by antonmedv** [comment]
BTW, do you want to work on another important (and interesting) part of Deployer?

**Comment by localheinz** [comment]
@antonmedv 

Not sure I have enough time, what do you suggest?

**Comment by antonmedv** [comment]
Implementing host selector: parsee and evaluator are needed.

**Comment by antonmedv** [comment]
https://github.com/deployphp/deployer/issues/2154

**Comment by localheinz** [comment]
@antonmedv 

Do you see a chance to backport this to `6.x`? I would open a pull request if you don't mind!

We need this in a project that currently depends on `6.x`.

**Pull request merged**
