### PR TITLE
Add StyleCI settings

### PR DESCRIPTION
**Pull request by lucasmichot**
So that we can use https://styleci.io

### CODE REVIEW

**Comment by lucasmichot** [comment]
screen shot 2015-06-18 at 09 38 45
Working nice with it, @GrahamCampbell can you maybe add a link to it ?

**Comment by ZeeCoder** [comment]
cool :+1:

**Comment by lucasmichot** [comment]
Well in fact @elfet @ZeeCoder it's more for you : when you go to the result page of your style check, when clicking on the logo, you should be able to get the following URL [StyleCI](https://styleci.io/repos/37314625) or something similar to be added to the README

**Comment by ZeeCoder** [comment]
Added it to the readme :)

**Comment by lucasmichot** [comment]
No @ZeeCoder , you are linking to my fork, not the original repository !

**Comment by ZeeCoder** [comment]
sh1t

**Pull request merged**
