### PR TITLE
Add a configuration file for Contao

### PR DESCRIPTION
**Pull request by leofeyer**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

This is the follow-up PR of #1906.

### CODE REVIEW

**Comment by antonmedv** [comment]
This is really small recipe. Do we really need it in repo?

**Comment by leofeyer** [comment]
So you think that a small recipe is less valuable than a large one? That does not make much sense to me. Also, why are you questioning this now after you have asked me to [recreate my PR](https://github.com/deployphp/deployer/pull/1906#issuecomment-619434687)? You could have just closed the first PR saying "sorry, the change is not relevant to us".

**Comment by antonmedv** [comment]
Sorry for mislead! Merged, I'm gonna fix test myself.

**Comment by leofeyer** [comment]
Thank you.

**Pull request merged**
