### PR TITLE
Fix time format for touch when deploying assets

### PR DESCRIPTION
**Pull request by wesleylancel**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | #718

### CODE REVIEW

**Comment by wesleylancel** [comment]
@antonmedv: any chance a release with this bugfix can be done? :)

**Comment by antonmedv** [comment]
Will do

**Comment by wesleylancel** [comment]
@antonmedv kind reminder, could you create a release with this bugfix? :)

**Comment by antonmedv** [comment]
Ohhh, okay.

**Pull request merged**
