### PR TITLE
The way to 100% test coverage (part 1)

### PR DESCRIPTION
**Pull request by pluseg**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

###
I've started to fix tests to get 100% coverage. It's important image thing as for me.

### CODE REVIEW

**Comment by pluseg** [comment]
I added each class refactoring as separate commit os it's convenient for cherry-pick.

**Comment by elfet** [comment]
First of all, thank you for your contribution to the project. I'm really appreciate that.

In open source there is a simple rule: no is temporary, yes is forever. If i say yes to this PR, we'll need to support those tests for every changes in recipes, and them are rapidly comes in. Those tests may bring 100% code coverage, but in coast of maintenance and slowing changes adoptions. In this project i nwhat ever aims to 100% code coverage. In fact i'm going to separate tests in two layers: one on unit tests for core (all what's in src and responds for task running and configuration) and integration tests for all recipes, tests what will be testing critical for recipes stuff, like success deploy, rollback, etc (i already start working on this, but code not in public for now). So, as maintainer of Deployer, i'm saying no to this PR for now.

**Comment by pluseg** [comment]
@elfet Bad news for me. 
Do you have a written list of main goals, principles and development trends of the project? Don't want to waste time for useless things.

**Comment by pluseg** [comment]
@elfet 
1. What're main features that you're planning in v5 and working right now?
2. What do you recommend to do for contributors?

**Comment by elfet** [comment]
1. Main feature it's deprecating other ssh clients and leaving only native ssh, so i want to fix as much as possible in v4 (while there is still way of using it if there is a bug).
2. For now, there is two labels: [good for beginner](https://github.com/deployphp/deployer/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+for+beginner%22) and [advanced+level](https://github.com/deployphp/deployer/issues?q=is%3Aopen+is%3Aissue+label%3A%22advanced+level%22). If you are planning something big it's good to open issue to discus it.

**Pull request closed without merging**
