### PR TITLE
Cachetool contrib recipe, add stat:clear command.

### PR DESCRIPTION
**Pull request by hardyjohnson**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

Cachetool contrib recipe, add stat:clear command.

### CODE REVIEW

**Comment by antonmedv** [comment]
I'm closing this PR for now in order to housekeeping. Fill free to reopen if needed.

**Comment by hardyjohnson** [comment]
Just curious is there a reason this PR wasn't considered for inclusion?

**Comment by antonmedv** [comment]
Sorry, doing housekeeping. Closed by accident. Please, rebase.

**Comment by antonmedv** [comment]
Nevermind. Did it myself.

**Comment by hardyjohnson** [comment]
Thank you!

**Pull request merged**
