### PR TITLE
Adding PATCH to Httpie

### PR DESCRIPTION
**Pull request by CaptainFalcon92**
Hello.

I've quickly added PATCH method to Httpie.
I need this to update messages in webhooks integrations (discord).

I currently respected the existing scheme, but i do think it would be better to allow more (any) methods by some refactoring.
Still i'd rather have it discussed here upfront before going further.

### CODE REVIEW

**Comment by CaptainFalcon92** [comment]
It would probably be more efficient to refactor into a single method.

```php
public function __construct(string $url, string $method)
{
    //    
    // cURL check...
    //

   $this->url = $url;
   $this->method = $method;
}

public static function get(string $url) : self
{
    return new self($url, 'GET');
}

public static function post(string $url) : self
{
    return new self($url, 'POST');
}

public static function put(string $url) : self
{
    return new self($url, 'PUT');
}

public static function patch(string $url) : self
{
    return new self($url, 'PATCH');
}
```

Let me know if your are willing to accept such evolution, and i'd commit to do the change.

Thank you, bye.

**Comment by CaptainFalcon92** [comment]
But there is one sure thing - currently i can't do but _get_ or _post_ as the property's private and there is no setter.

**Comment by antonmedv** [comment]
Let’s try to keep compatibility as much as possible. Adding new methods is ok. Opening private fields is also ok, but check out new function called fetch.

**Comment by CaptainFalcon92** [comment]
I will check `fetch` before. Thank you.

**Pull request merged**
