### PR TITLE
Fix issue 675

### PR DESCRIPTION
**Pull request by oanhnn**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | #675

### CODE REVIEW

**Comment by elfet** [comment]
What's with styleci?

**Comment by oanhnn** [comment]
@elfet 
StyleCI check and don't allow a blank line in before and after function body. 
Current in master branch, this error is exist. This PR is merged from master, so it have error.
What are you think about an other  PR to fix StyleCI ?

**Comment by elfet** [comment]
Yeah, PH for StyleCI

**Comment by oanhnn** [comment]
@elfet This PR is refactored

**Comment by oanhnn** [comment]
Ping @elfet @Baltazardoung

**Comment by elfet** [comment]
Ok!

**Comment by Baltazardoung** [comment]
OK!

**Pull request merged**
