### PR TITLE
Site-enabled folder for Caddy configs

### LINKED ISSUE #2876: Provision with two websites doesn’t work
One site works, the other displays an SSL error:
image

On my server, in home/deployer, I see two folders, with a Caddyfile in each.

_Originally posted by @sutcliffe121 in https://github.com/deployphp/deployer/discussions/2875#discussioncomment-1899022_

### PR DESCRIPTION
**Pull request by asamats**
- [ x] Bug fix #2876, #2948 

Added side-enabled folder for collecting all site's configs in one place. The purpose is to fix bugs and add the ability to run several sites.

### CODE REVIEW

**Comment by antonmedv** [comment]
Let’s now use sites-enabled, but instead use current dirs.

**Comment by asamats** [comment]
> Let’s now use sites-enabled, but instead use current dirs.

I thought about to use current dirs but every projects have self path. Do you suggest to add every paths to Caddyfile's main config?

**Comment by antonmedv** [comment]
Yes, let’s try to do this? It’s cool to have config located near deploy path. 

Or use /home/deployer/* and check what deploy_path is in it.

**Comment by codibit** [comment]
This actually solves the issue I was having with multiple deployments in the same host :)

**Comment by asamats** [comment]
@antonmedv Check changes. I hope it's appropriate.

**Comment by codibit** [comment]
I'm still getting issues with multiple sites in one server, as the domain configurations in Caddyfiles are not included within curly braces.
I created a new pull request: https://github.com/deployphp/deployer/pull/3115

**Pull request merged**
