### PR TITLE
[WIP] Docker test runner

### PR DESCRIPTION
**Pull request by x3ro**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | yes |
| Deprecations? | yes |
| Fixed tickets | none |

Since deployer's unit tests need at least an open SSHd running on the system, I thought that it might be nice to have reproducible builds inside a docker container. Let me know if this is something you would want to merge, so I can add some polish :smile:

### CODE REVIEW

**Comment by elfet** [comment]
This is awesome stuff! :+1: 
@x3ro great feature! I want to do it a lot.

**Comment by x3ro** [comment]
Glad you like the idea :) @everyone: Feel free to try it out, as I've only tested it on my system and would love to know if the scripts I've written work properly under all circumstances!

**Comment by elfet** [comment]
Can @deployphp/maintainer test it?

**Comment by x3ro** [comment]
Updated to work with latest php5.6-cli docker image. Interestingly, it currently hangs with 100% CPU usage on the `Deployer\Executor\ParallelExecutorTest::testParallel`. Any idea what that might be about?

**Comment by x3ro** [comment]
Also, now that [Docker is available for macOS and Windows](https://blog.docker.com/2016/07/docker-for-mac-and-windows-production-ready/) too, it becomes somewhat easier for people unfamiliar w/ docker to run the tests :)

**Comment by x3ro** [comment]
I'm still interested in seeing this merged :) How about everyone else?

**Comment by elfet** [comment]
Done! %)

**Comment by x3ro** [comment]
Oh :D To be honest I meant after fixing the issue with the hanging parallel tests and removing the `[WIP]` tag. Sorry for miscommunicating there. Any chance someone else could test this and/or give any insight into why the parallel tests might get stuck? How can I see the output of deployer for that test?

**Comment by elfet** [comment]
You need to install sockets too: http://php.net/manual/en/book.sockets.php 
` --enable-sockets`

**Comment by elfet** [comment]
Also *dep* command will try to run a few more processes in parallel mode.

**Pull request merged**
