### PR TITLE
Add default_selector and improve documentation on host labels and selection

### PR DESCRIPTION
**Pull request by marvinhinz**
- [ ] Bug fix #…?
- [x] New feature #3198
- [ ] BC breaks?
- [ ] Tests added?
- [x] Docs added?

The default_selector was pretty quick to implement. I also added some documentation. 

Would like to get some feedback on this!

congrats on the v7 release 🔥

### CODE REVIEW

**Comment by joelpittet** [comment]
This looks pretty solid solution @marvinhinz 👏

**Comment by joelpittet** [comment]
The documentation updates are a great touch too. Maybe could be shorter but they do describe the flexibility

**Comment by marvinhinz** [comment]
Thanks! In the meantime i thought about another comfort feature. In addition to a default_selector, we could use selector maps or aliases. I'm a fan easy to remember commands, so for a big project setup with many servers a deployment to production can be a bit complicated as you might need to enter something like `dep deploy stage=prod&role=web,role=special` everytime.

```
add('selector_map', [
    "prod" => "stage=prod&role=web,role=special",
    "staging" => "stage=staging",
]);
```
could then result in:

`dep deploy prod`

@antonmedv whats you opinion on this?

**Comment by marvinhinz** [comment]
@antonmedv seems like in the meantime you added documentation about the selectors itself, would you consider the default_selector functionality to be merged when i update this pr to the new documentation?

**Comment by joelpittet** [comment]
@antonmedv poking this as I still think it's a good idea but interested in your opinion/take as maintainer.

**Review by antonmedv — APPROVED** [review]

**Comment by joelpittet** [comment]
Whoa thanks @antonmedv for the quick turn around on the poke.

**Pull request merged**
