### PR TITLE
Added recipe for sulu 2.0

### PR DESCRIPTION
**Pull request by alexander-schranz**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | -

Added recipe for sulu 2.0

### CODE REVIEW

**Comment by antonmedv** [comment]
What is sulu?

**Comment by alexander-schranz** [comment]
@antonmedv Sulu is a symfony based open source CMS used for enterprise websites. see 
 - https://sulu.io
 - https://github.com/sulu/sulu-standard, https://github.com/sulu/sulu-minimal, https://github.com/sulu

**Comment by alexander-schranz** [comment]
@antonmedv is a 6.4 release planned? when yes is there a timeline?

**Comment by antonmedv** [comment]
Will release soon.

**Comment by alexander-schranz** [comment]
@antonmedv awesome thank you!

**Comment by alexander-schranz** [comment]
@antonmedv new year new release 😄?

**Pull request merged**
