### PR TITLE
Create Lumen recipe

### PR DESCRIPTION
**Pull request by mikestreety**
- [ ] Bug fix #…?
- [x] New feature?
- [ ] BC breaks?
- [ ] Deprecations?
- [ ] Tests added?
- [x] Changelog updated?

      Please, update CHANGELOG.md by running next command:
      $ php bin/changelog

- - -

Thanks for the great work! Makes deployment so much easier, thank you.

Following on from https://github.com/deployphp/deployer/pull/1207, this is a recipe that extends Laravel and customises for Lumen.

It unsets and makes private a lot of the Lumen specific commands (so when you run just `dep` they don't show up) and adds `artisan cache:clear` to the deployment. 

I wasn't sure about the tests or what "BC breaks" is.

Thanks

### CODE REVIEW

**Comment by mikestreety** [comment]
On review of the tests, it seems `setPrivate()` is not valid.

How would you recommended unsetting tasks? Maybe a `laravel.shared` recipe (or similar) is required which specifies the shared paths, but then Lumen and Laravel extend with their tasks instead?

**Comment by antonmedv** [comment]
Maybe just create separate recipe not extending laravel? I now think this is better approach.

**Comment by mikestreety** [comment]
Apologies. I only did as in the other Merge Request you recommended it

**Comment by antonmedv** [comment]
Yes, now I think maintaining  separate recipes will will be easier for us.

**Comment by lorisleiva** [comment]
Hi there 👋 

I'm not sure what it the point of overriding Laravel artisan tasks to noop functions.

If you're using Lumen, you should just not add any tasks that are not compatible with Lumen.

Furthermore, bear in mind that Lumen is extendable and you can cherry-pick the Illuminate components you need so this could actually break a valid Lumen application.

I think the best thing to do for Lumen is to simply override the Laravel recipe and provide a more appropriate default `deploy` task. The rest shouldn't need to change.

**Pull request closed without merging**
