### PR TITLE
Logger

### PR DESCRIPTION
**Pull request by rlacerda83**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes
| BC breaks?    | No
| Deprecations? |  No
| Fixed tickets | N/A

This pr allows you to create logs for the deployer.

I created based on https://github.com/dimoniet/deployer but simplified some things.

To log just set:
```
set ( 'log', 'fpath_to_log');
```

### CODE REVIEW

**Comment by elfet** [comment]
Logger going to 4.x

**Comment by rlacerda83** [comment]
What is the release date of version 4.x?

Excuse the question, it is why I really need the log. I use the log to log( = )) and to parse and record statistics of tasks and their execution times.

So I can see the bottlenecks of my deploy and improve some processes!

**Comment by elfet** [comment]
Logger will come in 4.x for sure. I think next week we will see first release candidate.

**Comment by elfet** [comment]
Check 4.x branch.

**Pull request closed without merging**
