### PR TITLE
Add repository_dirs option to select diretories from repository to de…

### PR DESCRIPTION
**Pull request by leocsilva**
…ploy

- [ ] Bug fix #…?
- [ x ] New feature?
- [ ] BC breaks?
- [ ] Deprecations?
- [ ] Tests added?
- [ ] Changelog updated?

      Please, update CHANGELOG.md by running next command:
      $ php bin/changelog

### CODE REVIEW

**Comment by antonmedv** [comment]
Hi, please, clarify why this code is needed. And what is doing, use cases.

**Comment by leocsilva** [comment]
Hi, @antonmedv !

Consider that I want to deploy this repository: https://github.com/cirosantilli/test-git-partial-clone-big-small

However, I want to choose only the "small" directory to deploy.

With this proposed change, I would choose only the directories that I want to deploy. So my recipe would look like this:

<? php
namespace Deployer;

require 'recipe / common.php';

set ('application', 'test');
set ('deploy_path', '/home/test');
set ('repository', 'https://github.com/cirosantilli/test-git-partial-clone-big-small');
set ('repository_dirs', ['small']);
...

then, only the "small" directory will be deployed.

I hope it has become clearer. Thanks!

**Comment by Baltazardoung** [comment]
👍 (with previous releases, I use git filter_branch for simulate this feature)


👍 (on my case with previous releases of 7.x, I use git filter_branch for simulate this feature)

**Comment by holmey** [comment]
Hi @antonmedv I think it would be very helpful to exclude files and directories from deployments. This is currently already possible with the exclude option in the rsync deploy method. Each of our repositories contains quality control tools, configurations for local versioning (e.g. Dockerfiles), source files needed to build the application, the .git directory, documentation, etc.
All these files are not required in the directory where the current release is located. Apart from the fact that a lot of resources may be used to store and move the files back and forth, sometimes these files may not even be there.

**Pull request closed without merging**
