### PR TITLE
Feature: Be able to specify web dir

### PR DESCRIPTION
**Pull request by ceesvanegmond**
Default; Symfonies web dir is 'web'. This features enables the user to change this default. 
Also; with the upcomming Symfony4 (where the web dir isn't web anymore); this should be quite handy.

| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

### CODE REVIEW

**Comment by antonmedv** [comment]
This is related only to server confiuration. Instead openning `current/web`, open `current/public`

**Comment by ceesvanegmond** [comment]
@anton It's not. You can change the root web location of Symfony. 
https://symfony.com/doc/current/configuration/override_dir_structure.html#override-the-web-directory

**Comment by antonmedv** [comment]
Please, rebase.

**Comment by ceesvanegmond** [comment]
@antonmedv Done!

**Comment by ceesvanegmond** [comment]
@antonmedv Why new milestone 7.0? This is fully backwards compatible right.

**Comment by antonmedv** [comment]
I think to refactor all that stuff related to paths - and put in into new major.

**Pull request closed without merging**
