### PR TITLE
Add a "find" mode

### PR DESCRIPTION
**Pull request by GaryPEGEOT**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | xx

Add a "find" mode, that prevent errors when writables folders are not empty, with files no-writables

### CODE REVIEW

**Comment by antonmedv** [comment]
What are use cases?

**Comment by GaryPEGEOT** [comment]
If, for example, a writable directory contain a file, created by a different user that the server, chmod mod will fail:
If a www-data user has created a file in a directory, chmod -R 775 my_dir with user "testuser" will fail.

Using find allow recursivity without changing permissions to files in it.

**Comment by antonmedv** [comment]
What about using sudo?

**Comment by GaryPEGEOT** [comment]
In my case sudo is not an option (Debian server without sudo installed), and root either.

**Comment by antonmedv** [comment]
For now it's only case in your situation, and you can simple override task. I don't think what this should be in common recipe.

**Pull request closed without merging**
