### PR TITLE
Laravel deploy task should not call cache:clear

### PR DESCRIPTION
**Pull request by leo108**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | No
| Deprecations? |  No
| Fixed tickets | N/A

`cache:clear` command will clear users' sessions if CACHE_DRIVER is the same as SESSION_DRIVER, I think users should call this task on demand instead of putting it in default deploy task.

### CODE REVIEW

**Comment by antonmedv** [comment]
ping @lasselehtinen @lucasmezencio

**Comment by lucasmezencio** [comment]
I think you're right @leo108..
LGTM @antonmedv.

Pull the trigger! 🙂

**Comment by antonmedv** [comment]
Please update changelog

**Comment by leo108** [comment]
@antonmedv Updated

**Comment by antonmedv** [comment]
@lasselehtinen sorry for distracting.

**Comment by barryvdh** [comment]
Imho you woud usually want to clear the cache upon deployments. I understand your issue, but you should split your redis cache database from the other redis databases (sessions, queues etc). This is the default for new 5.7 installs, see https://github.com/laravel/laravel/pull/4665

**Comment by matthew-muscat** [comment]
@antonmedv — i think the behaviour here should be that a cache clear is part of the recipe by default — as mentioned by @barryvdh , this is now the default in v5.7 installs, and can be configured by the user in earlier releases.

Flushing the cache during a deployment is what i would consider as expected behaviour — if you have your caches + sessions in the same location (ie: on the same redis db), then this is a bug in the setup or cache clearing logic, rather than an issue with how deployer is operating.

FYI — Laravel's `artisan cache:clear` command describes the action as the following.. 
`Flush the application cache`

**Pull request merged**
