### PR TITLE
Add password getter system for customize getting password. (#298)

### PR DESCRIPTION
**Pull request by ZhukV**
1. Add AskPasswordGetter (ask password before connecting)
2. Add CallabackPasswordGetter (gets password with call callbacks, Closures)

For more information, please see #298

### CODE REVIEW

**Comment by elfet** [comment]
Cool! :+1: 
Need more time to test, try to do all on weekend. 
Please, take a look at scrutinizer report for your PR: https://scrutinizer-ci.com/g/deployphp/deployer/inspections/a5866db1-224d-46b3-ad6a-e2e3e6f00568

**Comment by ZhukV** [comment]
Ok. I not see `composer.json`. 

```json
"symfony/console": "~2.6"
```

And i checks the `QuestionHelper` class exists for indicate SymfonyConsole of > 2.5 version.

**Comment by elfet** [comment]
Test coverage decreaseв a little bit. If you can keep them on same level, it will be 100% awesome :+1: 

PS Where are a lot issue to implement too, if you want take a look at #297. 
PPS Soon Deployer Roadmap will be ready.

**Comment by Max-Might** [comment]
I think PhpSecLib used to ask for password if it was empty, is that correct?

**Comment by ZhukV** [comment]
@Max-Might Yes, because password prompt before connection (in configuraiton `Configuration::getPassword`). The this feature will be worked in any 'adapters' for connection.

Example for ask password:

```php
server('production', 'domain.com')
    ->user('user')
    ->password() // <-- Default null (If null, the AskPasswordGetter will be created automatically)
    ->stage('production')
    ->env('deploy_path', '/var/www/domain.com');
```

**Comment by elfet** [comment]
Cool feature.

**Comment by DirtyB** [comment]
Will this work for passphrase in identityFile function?

**Comment by ZhukV** [comment]
@DirtyB, no, but this easy add.

**Comment by elfet** [comment]
Can you implement this too?

**Comment by ZhukV** [comment]
ok.

**Comment by ZhukV** [comment]
Adds.

Attention: by default, passphrase - '' (empty string). For use password getter automatically, you must set `null` for pass phrase.

```php
->identityFile(null, null, null)
```

P.S. Can set the *null* value for `$passPhrase` as default?

**Comment by elfet** [comment]
Thats ok, pass must be ‘’ as default.

**Comment by elfet** [comment]
Nice work. Need same one else too look at the PR before i'll merge it.

**Comment by ZhukV** [comment]
ping

**Comment by elfet** [comment]
I tested this feature, look good. Guys, please, test this feature too!

**Comment by elfet** [comment]
@ZhukV i'm going to implement event dispatcher in Deployer. Can you rewrite your feature by using dispatcher later?

**Comment by ZhukV** [comment]
:+1: No problem!

**Pull request merged**
