### PR TITLE
Remove useless else

### PR DESCRIPTION
**Pull request by lucasmichot**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

---

Remove useless else

### CODE REVIEW

**Comment by antonmedv** [comment]
?)

**Comment by lucasmichot** [comment]
@antonmedv - yes StyleCI does not take in consideration my change
I believe this is because you've define the fixers in the StyleCI dashboards: thus this file is never taken into consideration

**Comment by antonmedv** [comment]
Nope, it's emply

**Comment by lucasmichot** [comment]
Then StyleCI is not working properly then....

**Comment by lucasmichot** [comment]
See by yourself, the code is full of useless else, but StyleCI does not catch them....

**Comment by antonmedv** [comment]
I see only one changes file in this PR 
image

**Comment by lucasmichot** [comment]
Indeed this is the problem: I've modified StyleCI so that it checks the useless else, but StyleCI could not find anything

**Pull request merged**
