### PR TITLE
Added Lumen recipe

### PR DESCRIPTION
**Pull request by sandervankasteel**
This PR adds support for Lumen, this is PR is based on the work by Anton Medvedev with his Laravel recipe. 

| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

> Do not forget to add notes about your changes to [CHANGELOG.md](https://github.com/deployphp/deployer/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by antonmedv** [comment]
Why not to use laravel recipe or extend it? It's simple copy-paste recipe.

Also please rebase, test are falling.

**Comment by sandervankasteel** [comment]
You can't use the laravel recipe because it fails due to Artisan on Lumen not fully supporting all the commands that Artisan are available for Laravel. 

For example; `php artisan view:clear ` doesn't work on Lumen because Lumen doesn't has a viewstack. 

I will rebase, to make sure that the tests aren't failing anymore

**Comment by antonmedv** [comment]
What about extending laravel and only override `deploy` task?

**Comment by antonmedv** [comment]
Do not forget to add notes about your changes to CHANGELOG.md

**Comment by sandervankasteel** [comment]
Do you have an example for overriding ? Then I will implement it accordingly

**Comment by sandervankasteel** [comment]
Or do you mean something like this ?

```
<?php
namespace Deployer;

require 'recipe/laravel.php';

desc('Deploy your project');
task('deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:update_code',
    'deploy:shared',
    'deploy:vendors',
    'deploy:writable',
    'artisan:cache:clear',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
]);


```

**Comment by antonmedv** [comment]
Yes

**Comment by sandervankasteel** [comment]
Check, then I will make my modification accordingly! 😄

**Comment by antonmedv** [comment]
Okay.

**Pull request closed without merging**
