### PR TITLE
[master] Ignore composer.lock

### PR DESCRIPTION
**Pull request by lucasmichot**
Ignore composer.lock

### CODE REVIEW

**Comment by jacmoe** [comment]
The lock is in the repository because Deployer is an application and should be locked to specific versions of it's dependencies.

**Comment by jacmoe** [comment]
Composer.lock was added on February 2015 - check the history:
https://github.com/deployphp/deployer/commits/master/composer.lock

**Comment by lucasmichot** [comment]
This could apply to full project alongside with packages.json, bower.json and son on
In a package (even a binary one) like deployer, the constraints should be stricter and defined in `composer.json`

**Comment by lucasmichot** [comment]
If a dependencies package is buggy, we stay locked on it...

**Comment by jacmoe** [comment]
OK, if that is the intention, then your PR does not update composer.json accordingly :)

**Comment by lucasmichot** [comment]
?
> If a dependencies package is buggy, we stay locked on it...

**Comment by lucasmichot** [comment]
And I suppose unit tests are written on purpose, are they not?

**Comment by jacmoe** [comment]
> ?

People are building Deployer *at home* - it is the third option in the *installing Deployer* doc. How does removing *composer.lock* without modifying *composer.json* help?

**Comment by lucasmichot** [comment]
See phpunit / php-cs-fixer
- https://github.com/sebastianbergmann/phpunit/blob/master/composer.json  
- https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.12/composer.json (even less strict version) 

For both of these projects, people can build them and they do it very fine without any composer.lock

**Comment by jacmoe** [comment]
Those are libraries..

Composer has a composer.lock in their repository..

Anyway, let's wait for the Deployer project maintainers :)

**Comment by elfet** [comment]
Why composer.lock  disturbs you?

**Comment by lucasmichot** [comment]
It does not

**Pull request closed without merging**
