### PR TITLE
Use the Symfony progress bar when uploading directories.

### PR DESCRIPTION
**Pull request by Max-Might**
As discussed in pull request #282.

### CODE REVIEW

**Comment by elfet** [comment]
Test fails, can you check and fix it before i merge your PR?

**Comment by Max-Might** [comment]
The problem seems to be in symfony/console.
I have implemented the progress bar as per the docs:
http://symfony.com/doc/current/components/console/helpers/progressbar.html


The error is:
```
There was 1 error:

1) Deployer\FunctionsTest::testUpload
Argument 1 passed to Symfony\Component\Console\Helper\Helper::strlenWithoutDecoration() must implement interface Symfony\Component\Console\Formatter\OutputFormatterInterface, null given, called in /home/koce/Projects/deployer/vendor/symfony/console/Symfony/Component/Console/Helper/ProgressBar.php on line 545 and defined
```

**Comment by ZeeCoder** [comment]
Is there any progress here @Max-Might?
Did you try to fix the issue?

**Comment by Max-Might** [comment]
Yes but I can't find where the problem is :(
I have implemented the progress bar as per the docs.
I get the output stream from deployer and pass it to the progress bar.
The error is in the symfony code.

**Comment by ZeeCoder** [comment]
It's not the Symfony Component that's at fault here, look at the error more closely: https://travis-ci.org/deployphp/deployer/jobs/64213311#L264
It has something to do the way the tests work.

For some reason during that test the output you're passing to the Progress Bar by calling `output()` giving you `null`  instead of a proper `OutputFormatterInterface` object when the component calls the `getFormatter` method on it : https://github.com/symfony/Console/blob/2.6/Helper/ProgressBar.php#L545

I hope this helps. :)

**Comment by Max-Might** [comment]
Yes, this error happens only when we run the tests.
Is this how we create the output stream for the test procedure?

https://github.com/deployphp/deployer/blob/master/test/recipe/Helper/RecipeTester.php#L50

**Comment by ZeeCoder** [comment]
Seems so.
The `getFormatter` method needs stubbing.

**Comment by ZhukV** [comment]
So, this issue have a next problems:

1. The ProgressBar should be configurable.

As example:
```php
upload('/tmp/temporary.files', '/var/www/domain.com/tmp/temporary.files', true);
```
The third parameter indicated for use ProgressBar.

2. How this work in parallel?

**Comment by elfet** [comment]
What about parallel?

**Comment by GrahamCampbell** [comment]
Looks like this needs rebasing.

**Comment by elfet** [comment]
Please, rebase.

**Pull request closed without merging**
