### PR TITLE
Fix recursive chmod files issue

### PR DESCRIPTION
**Pull request by it-can**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | Possible
| Deprecations? | No
| Fixed tickets | #1675

### CODE REVIEW

**Comment by antonmedv** [comment]
Thanks for contributing.
Why writable_chmod_recursive should be performed only on dirs?

**Comment by it-can** [comment]
@antonmedv it uses the writable_dirs variable? It suggests chmodding directories. I don't think all files should be chmodded...

**Comment by antonmedv** [comment]
Why only dirs and not files?

**Comment by it-can** [comment]
Why would all files need to be chmodded to 755? For my projects it is not needed to chmod all my files within the storage directories to 755...

**Comment by antonmedv** [comment]
But what if users want to chmod files as well? This PR brings some kind of BC. What if someone expect this recipe to chmod files too?

**Comment by it-can** [comment]
@antonmedv agree...

**Pull request closed without merging**
