### PR TITLE
Created a file .php_cs with default header comment.

### PR DESCRIPTION
**Pull request by gpupo**
Before commit, we can run ``php-cs-fixer fix .`` and normalize all files of the project.
This can help on changes on header comment, doing this only in .php_cs.

Some fixers are commented because they need evaluation and testing to validate if not alter application behavior.

After accepted the PR, just run ``php-cs-fixer fix .`` on project root.

### CODE REVIEW

**Comment by elfet** [comment]
Thanks! But why we need it?

**Comment by gpupo** [comment]
Standard code style and licence header changes

**Comment by gpupo** [comment]
@elfet , check https://github.com/P3PO/deployer/commit/0cebfbec8e73d98028fa3bd0b640815ae82c57c7 and see  the changes that this will

**Comment by oanhnn** [comment]
Dear @gpupo ,
Your idea using `php-cs-fixer` is very good, but i think we should use coding style follows [PSR-1](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md) and other rulers. I was see the changes in [P3PO@ 0cebfbe](https://github.com/P3PO/deployer/commit/0cebfbec8e73d98028fa3bd0b640815ae82c57c7), i think it had inconsequential changes.
And i think @elfet  should implement himself.

**Comment by elfet** [comment]
@gpupo i see there are a lot of bad changes (`/**`->`/*`,...) And i dont think we need them.

**Comment by elfet** [comment]
@gpupo if you have arguments, let as know. For now, i'm closing this PR.

**Pull request closed without merging**
