### PR TITLE
Add initial support for custom php and php-cli binary.

### PR DESCRIPTION
**Pull request by gperdomor**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | Yes
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | #586 

This add initial support for configure a custom php for each server.

Some servers, need use php-cli to install vendors. This PR use a new env var (<code>composer_require_cli</code>) to handle that too

### CODE REVIEW

**Comment by oanhnn** [comment]
I think we not need env variable `composer_require_cli`

**Comment by elfet** [comment]
Agree. Maybe allow only to modify PATH?

**Comment by oanhnn** [comment]
Please see my comment in #586, and close this PR

**Comment by gperdomor** [comment]
@elfet @oanhnn in my case i need run <code>php-cli composer.phar install</code> because <code>php composer.phar install</code> not work. I can remove the <code>php-cli</code> env and override the composer task in my <code>deploy.php</code> file but maybe someone else have this problem.

**Comment by gperdomor** [comment]
Close for discuss in #586

**Comment by oanhnn** [comment]
@gperdomor You are installed both `php`, `php-cli` ?
Please show your version `php` and `php-cli`.

**Pull request closed without merging**
