### PR TITLE
Create Recipe for Pimcore

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
- [ ] Bug fix #…?
- [x] New feature?

Add Pimcore Recipe

- [ ] BC breaks?
- [ ] Deprecations?
- [ ] Tests added?
- [ ] Changelog updated?

      Please, update CHANGELOG.md by running next command:
      $ php bin/changelog

### CODE REVIEW

**Comment by Schrank** [comment]
@dpfaffenbauer Thanks for your PR! Would you mind running docgen?

> Please, run bin/docgen and commit next files:
> ?? docs/recipe/pimcore.md

**Comment by dpfaffenbauer** [comment]
@Schrank just did, thanks for the reminder.

**Comment by Schrank** [comment]
Thanks @dpfaffenbauer! Do you want to add some default deploy steps before merging?

https://github.com/deployphp/deployer/blob/master/recipe/shopware.php#L198-L217

**Comment by Schrank** [comment]
Little sidenote: It is better to add tasks with before/after instead of overwriting deploy task itself 😅

**Comment by dpfaffenbauer** [comment]
you mean adding a after/before to run eg `deploy:pimcore:rebuild-classes` ?

**Comment by dpfaffenbauer** [comment]
@Schrank added what I think you mean :)

**Comment by dpfaffenbauer** [comment]
💪  🍻

**Comment by antonmedv** [comment]
Released in beta.26.

**Pull request merged**
