### PR TITLE
Use POSIX style if

### LINKED ISSUE #1445: commandSupportsOption: `[[: not found`
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.0.3
| Local Machine OS  | Ubuntu16 lts
| Remote Machine OS | N/A

### Description 
when running my recipe I can see a `[[: not found` error, which is triggered by a call to `commandSupportsOption()`. I guess there is some kind of incompatibility with bash or similar, which makes this simple command trigger this error

### Output log
```sh
[localhost] > cd /cluster/www/www/www/xxx_relaunch/.build && (if [[ $(man ln 2>&1 || ln -h 2>&1 || ln --help 2>&1) =~ '--relative' ]]; then echo 'true'; fi)
[localhost] < sh: 1: [[: not found
```

### Env
```
php -v
PHP 7.0.26-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Nov 29 2017 09:51:01) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.26-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.18.0~linux-x64-non_zts70, https://blackfire.io, by SensioLabs
```

### PR DESCRIPTION
**Pull request by staabm**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes or No
| New feature?  | Yes or No
| BC breaks?    | Yes or No
| Deprecations? | Yes or No
| Fixed tickets | #1445

Will hopefully fix #1445 . not tested yet.

### CODE REVIEW

**Comment by staabm** [comment]
before this change
```
[localhost] > if [[ $(man svn 2>&1 || svn -h 2>&1 || svn --help 2>&1) =~ 'status' ]]; then echo 'true'; fi
[localhost] < sh: 1: [[: not found
```

after this change
```
[localhost] > if [ $(man svn 2>&1 || svn -h 2>&1 || svn --help 2>&1) =~ 'status' ]; then echo 'true'; fi
[localhost] < sh: 1: [: svn(1): unexpected operator
```

so it changed one warning for another.. not sure what the correct patch should look like

**Comment by antonmedv** [comment]
Well, `[[` is much easier to use. Try to install bash on your system.

**Comment by staabm** [comment]
I have a regular ubuntu where bash is installed per default.

**Comment by antonmedv** [comment]
So check what login with deployer user has bash by default. `[[: not found` bash has `[[`.

**Comment by staabm** [comment]
```
dep run --hosts=devmst16 -- 'echo $0'
bash
```

I guess I use bash..

**Comment by zorn-v** [comment]
On ubuntu `/bin/sh` is symlink to `dash` not `bash`

**Comment by staabm** [comment]
@zorn-v  thx for your input.

both suggested commands do not work.
the mentioned commands do not return "TRUE" when the given option is supported by the command

1st: 
runs withour error but does not provide the correct result

2nd: 
contains a syntax error

I tried to fix the second to
```sh
test("[ \"\$(case `man $command 2>&1 || $command -h 2>&1 || $command --help 2>&1` in *$option*)  echo '1'; esac)\" = '1' ]");
```

but this doesnt provide the correct results either.

any insights?

**Comment by staabm** [comment]
Ping @zorn-v

**Comment by zorn-v** [comment]
Maybe need some escaping. I test those command in shell.

**Comment by zorn-v** [comment]
I think it need to do all things via /bin/bash (fuck FreeBSD) or introduce some var (default to /bin/bash, not /bin/sh - important for ubuntu) that tells thru wich shell commands should execute (/usr/local/bin/bash for FreeBSD for ex.) than torment with such things...

**Comment by antonmedv** [comment]
Yes, I think car for bash is ok. I think we can relay on bash3 as it can be found anywhere

**Comment by staabm** [comment]
I dont know exactly what you guys are talking about, as I am not a bash guy.

In case you want me to adjust a bit in this PR please give me a more concrete hint and I am happily adjust whatever is required.

**Comment by antonmedv** [comment]
Problem here is more wide: it's nice to have `[[` `]]` as it more flexible. Maybe instead we need to always use bash.

**Comment by zorn-v** [comment]
I just try to replace "bashism" like `=~` in "POSIX". I don't know what excatly "not working" at you. Then I think about not breaking mind, and use `bash` as shell for ALL commands (I suspect that in deployer `/bin/sh` is used in `test` php function)

**Pull request closed without merging**
