### PR TITLE
Remove useless else.

### PR DESCRIPTION
**Pull request by lucasmichot**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

### CODE REVIEW

**Comment by antonmedv** [comment]
I think removing else in this cases make  code less readable.

**Comment by barryvdh** [comment]
I think that in this case, switching the expected values would be more readable, when removing the `else`

```php
public function get($name)
{
	if ( ! $this->has($name)) {
		return $this->throwNotFound($name);
	}
	
	return $this->values[$name];
}
```

But I guess that is just personal preference :)

**Comment by antonmedv** [comment]
Yes, personal preference. But if it make sense - ok

**Comment by lucasmichot** [comment]
Feel free to re-open it if you feel so

**Pull request closed without merging**
