### PR TITLE
Fix problems with use many tasks with equals name in group

### PR DESCRIPTION
**Pull request by elfet**
Based on PR #332
Bug from #331

### CODE REVIEW

**Comment by elfet** [comment]
@deployphp/maintainer lets test this and discuss!

**Comment by elfet** [comment]
Do we really need tasks ids?

**Comment by ZhukV** [comment]
Yes, for correct control in informer system.

As example: In my deploy system i rewrite informer for run any logic after fail tasks. And, if i have a two task with name `some_foo`, i can control runs with this identifier.

**Comment by elfet** [comment]
@ZhukV i think it's a little bit complicated. I'd fixed this myself without introduction tasks ids. 
Check this out:  9667b4c7

**Pull request closed without merging**
