### PR TITLE
fix bug recipe common deploy:writable httpUser run ps user to user:20

### PR DESCRIPTION
**Pull request by sdhou**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  |  No
| BC breaks?    |  No
| Deprecations? |  No
| Fixed tickets | N/A

### CODE REVIEW

**Comment by elfet** [comment]
Hi, what is this?

**Comment by jessiejia** [comment]
When i have a user named  gitlab-www for nginx , the `ps axo user,comm` will get 'gitlab-+'. 
This will lead to the failure of the following tasks

**Comment by elfet** [comment]
So use can simple set http_user param?

**Comment by jessiejia** [comment]
yes, http_user is useful for that .
but i think this one is more cheap .
besides that ,  `http_user` is unsetable  in current code

**Comment by elfet** [comment]
How is unsettable? You can use set.

**Comment by jessiejia** [comment]
Yes, it works.

**Pull request closed without merging**
