### PR TITLE
Updated writable dirs

### PR DESCRIPTION
**Pull request by zupolgec**
As per https://laravel.com/docs/5.2#configuration

Q | A
------------ | -------------
Bug fix? | yes
New feature? | no
BC breaks? | no
Deprecations? | no
Fixed tickets | -

### CODE REVIEW

**Comment by oanhnn** [comment]
Thank you! Please edit your comment for this PR follow this format!

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | -

**Comment by zupolgec** [comment]
@oanhnn did that

**Comment by oanhnn** [comment]
Thank you!
Now deployer support Laravel 5.1+ :beers:

**Comment by elfet** [comment]
BC breaks? Laravel 4/5?

**Comment by zupolgec** [comment]
This recipe was already for Laravel 5+
The writable folders for Laravel 5.1+ are `bootstrap/cache` and `storage`.
For Laravel 5.0 the documentation says `storage` and `vendor`. But in my experience there is no need to make the `vendor` folder writable. It was briefly required when, in the beginning of the 5.0 development, the framework used to create files and put them in the `vendor` folder. If opening a pull request on the documentation to fix that

**Comment by zupolgec** [comment]
@elfet I tried creating a new Laravel 5.0 project and it still uses the `vendor` folder. Maybe we should point out in the documentation that this recipe is for Laravel 5.1 (the LTS version) or later

**Comment by oanhnn** [comment]
I think we should follow Laravel 5.1, because it is LTS. :smile: 
This means Laravel team recommend users using this version. And we should support it.

**Pull request merged**
