### PR TITLE
Adding artisan migration helpers

### PR DESCRIPTION
**Pull request by filpgame**
Adding Laravel's `artisan migration` helpers

Q | A
------------ | -------------
Bug fix? | no
New feature? | yes
BC breaks? | no
Deprecations? | no
Fixed tickets | n/a

### CODE REVIEW

**Comment by oanhnn** [comment]
Please edit comment and prepend table 

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | n/a

Migartion should be executed without option `--force`

**Comment by elfet** [comment]
Agree, no `--force`.

**Comment by filpgame** [comment]
But in `production` environment, the migration command will be ignored without `--force`

**Comment by elfet** [comment]
Is `--force` used only for asks for a confirmation? May be there is an not-interactive mode?

**Comment by philbates35** [comment]
Pretty sure all `--force` does is to automatically proceed when it asks for confirmation. @flipgame is right, without it the command would be cancelled.

**Comment by barryvdh** [comment]
Agreed, you need `--force`.

Perhaps also add `php artisan db:seed` and a `php artisan migrate:status` to check before running migrate?

Not sure if it's possible to do the confirm on the Deployer side, to be safe?

**Comment by elfet** [comment]
It's possible, but what happens if you run `php artisan migrate --force` if there no migrations?

**Comment by philbates35** [comment]
It just says "nothing to migrate". Force is purely just to get past the "you're in production, are you you sure you want to do this?" prompt.

**Comment by elfet** [comment]
Do we need `deploy:migrate` in `deploy` task?

**Comment by barryvdh** [comment]
> Do we need deploy:migrate in deploy task?
I wouldn't do that by default.

**Comment by oanhnn** [comment]
I think this problem will be resolved in #622 
Thank you @filpgame about your contribution.

**Pull request closed without merging**
