### PR TITLE
#929: Moved deployer/phar-update to suggest instead of raw dependency

### PR DESCRIPTION
**Pull request by ceesvanegmond**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | #929

This small pullrequest moves deployer/phar-update to the suggest. See ticket #929

### CODE REVIEW

**Comment by ceesvanegmond** [comment]
@elfet The build is failing because of the use of ```Deployer\Component\PharUpdate\Console\Command``` and ```Deployer\Component\PharUpdate\Console\Helper```. Does deployer really need those in ```Application```?

**Comment by elfet** [comment]
For phar - yes. Need to check if it's phar.

**Comment by ceesvanegmond** [comment]
@elfet Can't we just remove those lines of code?

**Comment by elfet** [comment]
@ceesvanegmond no. phar update will be broken then.

**Comment by lucasmichot** [comment]
Maybe using https://github.com/padraic/phar-updater would be a good alternative then ?

**Comment by elfet** [comment]
@lucasmichot no, i think current impl is better. I think it's possible only to install it in dev mode, and only for building phar.

**Comment by lucasmichot** [comment]
Sorry @elfet , it's a misunderstanding; I meant:
instead of using `herrera-io/phar-update` (abandonned) in dev depdencies, we should use `padraic/phar-updater` in dev-dependecies

**Comment by elfet** [comment]
@lucasmichot no :) adraic/phar-updater is another impl with different features, we will stick with deployer/phar-updater (fork of herrera-io/phar-update).

**Comment by elfet** [comment]
Done. Updated deployer/phar-update.

**Pull request closed without merging**
