### PR TITLE
Fix time format for touch when deploying assets

### PR DESCRIPTION
**Pull request by wesleylancel**
See #718

| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | #718

### CODE REVIEW

**Comment by wesleylancel** [comment]
Sorry for the three commits, quickly used the online Github editor, please squash when merging.

Should I create a separate PR for 4.x or will this be backmerged?

**Comment by antonmedv** [comment]
Please, fix tests and yes, send another PR for v4.

**Comment by wesleylancel** [comment]
@antonmedv: fixed

**Comment by antonmedv** [comment]
@wesleylancel thanks for fixing long live bug))

**Pull request merged**
