### PR TITLE
[httpie] New private method to create the headers

### PR DESCRIPTION
**Pull request by joanhey**
So will be easier to modify it and it don't pollute the `send()` method.

- [ ] Bug fix #…?
- [ ] New feature?
- [ ] BC breaks?
- [ ] Tests added?
- [ ] Docs added?

      Please, regenerate docs by running next command:
      $ php bin/docgen

### CODE REVIEW

**Comment by antonmedv** [comment]
Let’s join all pr into one.

**Comment by joanhey** [comment]
I have more commits, but depend in if previous PRs are accepted.

**Comment by joanhey** [comment]
But I can join the last 4 PRs

**Comment by joanhey** [comment]
Joined in #3098

**Pull request closed without merging**
