### PR TITLE
Add writable_setgid_group option to enable sticky gid writable dirs

### PR DESCRIPTION
**Pull request by nosnickid**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | n/a

The new option 'writable_setgid_group' allows deployments that use a common group between web server user and project user, using the existing deploy:writable task.

It's similar to https://github.com/deployphp/deployer/issues/404#issuecomment-126986068, but it also works with default recipes.

Test included.

### CODE REVIEW

**Comment by oanhnn** [comment]
What's different?
```
$ setfacl -R -m u:"www-data":rwX -m u:`whoami`:rwX tmp
$ setfacl -dR -m u:"www-data":rwX -m u:`whoami`:rwX tmp
```
Vs
```
$ setfacl -R -m u:"www-data":rwX g:deployers:rwX u:`whoami`:rwX tmp
$ setfacl -dR -m u:"www-data":rwX  g:deployers:rwX u:`whoami`:rwX tmp
```

We need document and more test cases.
```
$hasfacl = run("getfacl -p $dir | grep \"^user:$httpUser:.*w\" | wc -l")->toString();
```

**Comment by elfet** [comment]
May be add fallback to this:
```php
run("chgrp {{common_group}} $dirs");
run("chmod 775 $dirs");
```

**Comment by nosnickid** [comment]
I do intend to get back to this update and get the docs updated, been busy with other things.

0775 would be marginally better but my 2775 is better still as an option, once I get around to documenting it.

**Comment by elfet** [comment]
Cool!

**Comment by nosnickid** [comment]
I've been looking at this.  I've taken the code in the first comment for #404 and added my extra setgid method.

I'd like to write a test that confirms each mode runs the expected command.  I don't think that I can write a reliable test that tries to examine the outcome of each of the commands because they depend on things such as a group the user is in, or an OSX command in a Linux environment.

I don't see a simple way to set an expected flag. I've passed ['verbosity' => 999] options to `$this- >exec` in the test and captured the output, so I could scan the output for Run: lines.  Eugh.

Any better suggestions?

**Comment by elfet** [comment]
Documentation will be very helpful.

**Comment by nosnickid** [comment]
I've made a start on the docs:

https://github.com/nosnickid/docs/blob/master/recipes.md#deploywritable_dirs

**Comment by elfet** [comment]
Hi,

Since in this PR no progress, i'm closing it.

**Pull request closed without merging**
