### PR TITLE
Update default cachetool version to 9.0.0 (PHP 8.1 compatible)

### PR DESCRIPTION
**Pull request by schmengler**
- [ ] Bug fix #…?
- [ ] New feature?
- [ ] BC breaks?
- [ ] Tests added?
- [ ] Docs added?

      Please, regenerate docs by running next command:
      $ php bin/docgen

### CODE REVIEW

**Comment by Schrank** [comment]
What do you think about getting the PHP version and depending on the version we load the right cachetool version?

**Comment by schmengler** [comment]
I wouldn't need it but certainly nice to have

**Comment by dreadnip** [comment]
I proposed something similar a while ago: https://github.com/deployphp/deployer/pull/3375

It was merged into the V8 branch, which was deleted shortly after.

**Comment by antonmedv** [comment]
Separate development in v8 branch was a mistake. Very different to track changes.

**Pull request merged**
