### PR TITLE
Added default port number into Host (#closes 1227)

### PR DESCRIPTION
**Pull request by dakur**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | #1227

### CODE REVIEW

**Comment by lucasmezencio** [comment]
Please! Merge this! :)

**Comment by antonmedv** [comment]
What purpose of this?

**Comment by lucasmezencio** [comment]
@antonmedv because of this error @dakur mentioned in #1227 :

```
[10.0.0.2] > rsync -azP -e 'ssh -p ' ../dist/ someuser@10.0.0.2:/var/www/web/dev/releases/75
[10.0.0.2] < Bad port '-l'
```

The default port for SSH connections is 22, then we should not have to provide this all the time.

**Comment by antonmedv** [comment]
I think is no port provided when `-e 'ssh -p '` should not be added.

**Comment by dakur** [comment]
@antonmedv I think you did not understand it. `-e 'ssh -p '` is what it does now. My fix is to add the port number there.

**Comment by antonmedv** [comment]
What is use don't put port number in host declaration but have different port in ~/.ssh/config? This will break everything. If no port is specified, omit `-e 'ssh -p '`.

**Comment by lucasmezencio** [comment]
@antonmedv sure. I think I got you.

**Comment by dakur** [comment]
@antonmedv I have no port specified in `~/.ssh/config`, I have no `~/.ssh/config` at all. If I omit `port` in host declaration, `-e 'ssh -p '` is called automatically by Deployer. That's why started this issue and made that PR.

**Comment by antonmedv** [comment]
@dakur your solution isn't correct (see my comment above).

> `-e 'ssh -p '` is called automatically by Deployer

This is problem in first place, and the bug what should be fixed.

**Comment by dakur** [comment]
Ok, looks like it was fixed in #1240

**Pull request closed without merging**
