### PR TITLE
use md5 of task name for section id in gitlab ci

### LINKED ISSUE #3787: Gitlab CI collapsible sections use unique section header name.
Currently script uses unix timestamp ($start) as both start time + section name (same goes for section_end - using $start).

This causes collision within multiple tasks running in the same second cause it's used by gitlab for grouping.
```
           $this->output->writeln("\e[0Ksection_start:{$start}:{$start}[collapsed=true]\r\e[0K{$task->getName()}");
           $this->output->writeln("\e[0Ksection_end:{$endTime}:{$start}\r\e[0K");
```

I think better solution is to use slug of task name:

```
           $this->output->writeln("\e[0Ksection_start:{$start}:{$slug}[collapsed=true]\r\e[0K{$task->getName()}");
           $this->output->writeln("\e[0Ksection_end:{$endTime}:{$slug}\r\e[0K");
```

or to be more "unique" - combination of task name slug + startTime:

```
           $this->output->writeln("\e[0Ksection_start:{$start}:{$slug}_{$start}[collapsed=true]\r\e[0K{$task->getName()}");
           $this->output->writeln("\e[0Ksection_end:{$endTime}:{$slug}_{$start}\r\e[0K");
```

### PR DESCRIPTION
**Pull request by fliespl**
Resolves #3787

- [X] Bug fix #3787
- [ ] New feature?
- [ ] BC breaks?
- [ ] Tests added?
- [ ] Docs added?

### CODE REVIEW

**Comment by fliespl** [comment]
@antonmedv when do you think this might get released? No rush - just checking :) I was doing updates of deployer and noticed this is still a problem on 7.4.0.

**Comment by antonmedv** [comment]
This week ;)

**Comment by mrhackcz** [comment]
Hi @antonmedv , any news about next release ? :) Its kinda annoying
image

**Comment by antonmedv** [comment]
Well. This week)

**Pull request merged**
