### PR TITLE
Fix missing setHidden method

### PR DESCRIPTION
**Pull request by cve**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | Yes
| BC breaks?    | Yes
| Deprecations? | Yes
| Fixed tickets | N/A

### CODE REVIEW

**Comment by elfet** [comment]
What symfony console version?

**Comment by cve** [comment]
How can I check that? :) I have a project with Symfony 2.7

**Comment by elfet** [comment]
I see. I think it's better not to delete it, but feature check it.

**Comment by cve** [comment]
You are right

**Pull request merged**
