### PR TITLE
fixed uploading of files containing spaces

### LINKED ISSUE #1077: scp filenames with spaces doesnt work
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.2.1
| Local Machine OS  | ubuntu16.04 lts
| Remote Machine OS | ubuntu16.04 lts

```
php -v
PHP 7.0.16-4+deb.sury.org~xenial+1 (cli) (built: Mar  2 2017 10:36:04) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.16-4+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.15.0~linux-x64-non_zts70, https://blackfire.io, by Blackfireio Inc.
```

### Description 
the copy using scp fails, as arguments are not properly escaped.

### Steps to reproduce
copy a directory which contains file, containing a space in the filename with the following task

```
task('deploy:update_code', function () {
    upload('.', '{{release_path}}');
});
```

### Output log

```
 [Symfony\Component\Process\Exception\ProcessFailedException]
  The command "scp -P '22' -i '/home/mstaab/.ssh/id_rsa' -o ControlMaster=auto -o ControlPersist=5 -o ControlPath='~/.ssh/YYY@XX:22' '/my/local/path/vendor/filp/whoops/docs/Framework Integration.md' 'mstaab@XYX:/my/remote/path/test123/releases/1/vendor/filp/whoops/docs/Framework Integration.md'" failed.
  Exit Code: 1(General error)
  Working directory: /my/local/path/
  Output:
  ================
  Error Output:
  ================
  scp: ambiguous target
```

### PR DESCRIPTION
**Pull request by staabm**
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 4.2.1
| Local Machine OS  | ubuntu16.04 lts
| Remote Machine OS | ubuntu16.04 lts

```
php -v
PHP 7.0.16-4+deb.sury.org~xenial+1 (cli) (built: Mar  2 2017 10:36:04) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.16-4+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.15.0~linux-x64-non_zts70, https://blackfire.io, by Blackfireio Inc.
```

### Description 
the copy using scp fails, as arguments are not properly escaped.

### Steps to reproduce
copy a directory which contains file, containing a space in the filename with the following task

```
task('deploy:update_code', function () {
    upload('.', '{{release_path}}');
});
```

### Output log

```
 [Symfony\Component\Process\Exception\ProcessFailedException]
  The command "scp -P '22' -i '/home/mstaab/.ssh/id_rsa' -o ControlMaster=auto -o ControlPersist=5 -o ControlPath='~/.ssh/YYY@XX:22' '/my/local/path/vendor/filp/whoops/docs/Framework Integration.md' 'mstaab@XYX:/my/remote/path/test123/releases/1/vendor/filp/whoops/docs/Framework Integration.md'" failed.
  Exit Code: 1(General error)
  Working directory: /my/local/path/
  Output:
  ================
  Error Output:
  ================
  scp: ambiguous target
```

Fixes #1077

### CODE REVIEW

**Comment by elfet** [comment]
Please, read contributing guide.

**Comment by staabm** [comment]
not sure what exactly you are refering to... I copied over the bug description from  #1077 and added a changelog entry.

**Comment by elfet** [comment]
Can you combine this two PRs? And give a little description about how this fixes a bug? Now, i little confused about it.

**Comment by staabm** [comment]
As those are 2 different bugs, I separated them intenionally. one only affects only the download() helper, the other one only the upload() helper.

If you still think it should be combined, I will do so of course.

**Comment by elfet** [comment]
Sorry, don't understand what it was two bugs. A little info about a bug will be helpful.

**Comment by staabm** [comment]
we fix a too agressive escaping of the local-scp-part with this PR which lead to a error while uploading files containing spaces in the filename. 

Will update the changelog after lunch

**Pull request merged**
