### PR TITLE
Make sure to use the correct PHP binary with existing Composer

### PR DESCRIPTION
**Pull request by Toflar**
Not sure if this is correct but otherwise, the wrong PHP binary will be used.

### CODE REVIEW

**Comment by Schrank** [comment]
@antonmedv you changed this three months ago, but I would agree with @Toflar that we want to run composer with the correct php version, which can be configured by using bin/php.

https://github.com/deployphp/deployer/commit/45e4708aad31931805e37387ccb7940cae9c9149

**Comment by Toflar** [comment]
Actually the change 3 months ago caused my deployment to suddenly fail ;)

**Comment by Schrank** [comment]
Good to know, you only need it every three months 🙈

**Comment by Schrank** [comment]
@Toflar You know for a quick-fix you can just overwrite the task?

**Comment by clxmstaab** [comment]
duplicate of https://github.com/deployphp/deployer/pull/2946 ?

**Pull request merged**
