### PR TITLE
Move contributing to .github folder.

### PR DESCRIPTION
**Pull request by lucasmichot**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

### CODE REVIEW

**Comment by barryvdh** [comment]
Meh, makes it harder to find manually

**Comment by barryvdh** [comment]
(I'm not the maintainer, so could be that @antonmedv does like it)

**Comment by antonmedv** [comment]
I like it) But does github will link there then?

**Comment by lucasmichot** [comment]
Feel free to re-open this PR @antonmedv

**Pull request closed without merging**
