### PR TITLE
Updated phpseclib requirement for v2.x

### PR DESCRIPTION
**Pull request by ArjandeV**
@elfet can you also fix it in the 2.0 version so we can use it in production, please also add tag if merged.

### CODE REVIEW

**Comment by elfet** [comment]
Done.

**Comment by oanhnn** [comment]
I have error installing deployer v2.0.1
```shell
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for deployer/deployer 2.0.1 -> satisfiable by deployer/deployer[v2.0.1].
    - deployer/deployer v2.0.1 requires phpseclib/phpseclib ~2.0@dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```
I think this might be fixed by:
```json
"phpseclib/phpseclib": "2.0.*@dev"
```

**Comment by elfet** [comment]
Thanks! Fixed.

**Comment by elfet** [comment]
Error again.

**Comment by elfet** [comment]
Solution: require phpseclib.
```
composer require phpseclib/phpseclib:2.0.*@dev
composer require deployer/deployer:2.0.1
```

**Comment by elfet** [comment]
Done.

**Comment by GrahamCampbell** [comment]
@elfet The correct solution would be to set the "minimum-stability", not to require a dependency twice.

**Pull request closed without merging**
