### PR TITLE
Remove the Contao recipe again

### PR DESCRIPTION
**Pull request by leofeyer**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

The symfony4 recipe no longer sets the `symfony_env` variable, therefore this PR removes it from the contao recipe as well (because it is based on the symfony4 recipe).

### CODE REVIEW

**Comment by leofeyer** [comment]
@antonmedv Regarding your [comment](https://github.com/deployphp/deployer/pull/2043#issuecomment-621946984): After merging this PR, the recipe will become very small indeed, therefore feel free to remove it completely.

**Comment by antonmedv** [comment]
Looks like contao is just Symfony

**Comment by leofeyer** [comment]
Yes, pretty much meanwhile. So let's remove the recipe again. Do you want me to create a PR?

**Comment by antonmedv** [comment]
Yes, please.  As it grows in completely abd diverges from Symfony feel free to add it as recipe.

**Comment by leofeyer** [comment]
I have adjusted the PR so it reverts the changes from #2043. Sorry for the back and forth. 🙈

**Pull request closed without merging**
