### PR TITLE
FEATURE: Add Flow-Framework deployer recipe

### PR DESCRIPTION
**Pull request by mficzel**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

With this recipe projects based on the Flow-Framework (https://flow.neos.io/) and Neos-CMS (https://www.neos.io) can be deployed.

### CODE REVIEW

**Comment by mficzel** [comment]
I file this pr against master because in the past new base-recipes were often added in dot-releases. If requested i will gladly rebase on 4.x.

**Comment by elfet** [comment]
I think it's can be separate repo with this recipe.

**Comment by mficzel** [comment]
It is a base recipe like those for laravel, symfony or typo3 wich are part of the main deployer-repository, that is why i think this belongs here.

In a separate repo the projects using this would either copy the recipe-file or use a custom deployer build wich both is a hurdle.

**Comment by elfet** [comment]
Closing as fameless.

**Comment by mficzel** [comment]
@elfet what would make this not fameless ... creating an issue and collecting +1 comments?

**Comment by elfet** [comment]
@mficzel community. https://www.google.co.th/search?q=link%3Aflow.neos.io

**Comment by elfet** [comment]
Why you don't want to create separate project with your recipe for your framework?

**Comment by mficzel** [comment]
@elfet Just to make it clear. Flow is not my personal framework it has some community around europe (especially germany) and is already some years old. 

I am part of the neos and flow team but i am still pretty new there. In that role i work on making the use easier for new users ... supporting deployer is part of that.

Maybe a clarification about how contributing to deployer works and what kind of code is welcome would help. I do'nt want to steal your time with pr's that do'nt go in and would rather compile the needed informations you need beforehand.

**Comment by mficzel** [comment]
Maybe some statistics are interesting here:

- flow has 221 420 installs ... https://packagist.org/packages/typo3/flow
- neos (based on flow) has 118 388 installs ... https://packagist.org/packages/typo3/neos

Note: The namespace typo3 will be removed from the project in the future this was started as a typo3-rewrite but grew to a seperate project.

**Comment by elfet** [comment]
Looks like a lot (118 388) installs. 
I think we can add it. I'm planing to find some solution for management  a lot of recipes.

**Pull request merged**
