### PR TITLE
Added variable for composer command path

### PR DESCRIPTION
**Pull request by zupolgec**
Now we can specify a path for the composer command, avoiding the download

Q | A
------------ | -------------
Bug fix? | no
New feature? | yes
BC breaks? | no
Deprecations? | no
Fixed tickets | -

### CODE REVIEW

**Comment by oanhnn** [comment]
why are we need this feature?

**Comment by zupolgec** [comment]
Because sometimes we have composer on the server, but cannot be reached with a simple `composer`. On a server I use for deploy the command is `composer.phar`. With this setting we can avoid downloading composer

**Comment by oanhnn** [comment]
Yes. Can you add a PR to [document](https://github.com/deployphp/docs) about this feature ?

**Comment by zupolgec** [comment]
Docs added!

**Comment by elfet** [comment]
But you can always add it. In .bashrc:
```
alias composer='/bin/composer'
```

**Comment by zupolgec** [comment]
Ok, seems fair :+1:

**Comment by zupolgec** [comment]
@elfet I checked and I already had that line in my .bashrc
The problem lies in the commandExist function. The `hash` command doesn't "follow" aliases. Maybe you should change that to `command`.
http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script

**Comment by lbarulski** [comment]
We keep `composer.phar` in project repository to keep its version under control - there were some situations when phar file on getcomposer was broken or installation based on the same `composer.lock` gave us different results on different `composer.phar` versions (dev vs prod)...

:+1: for feature

**Comment by oanhnn** [comment]
Thank you!

**Comment by elfet** [comment]
Awesome!

**Comment by mbrodala** [comment]
Another usecase: sometimes there are various PHP versions available for CLI and you want to ensure the correct one is used. With this change you can simply prepend it, thus :+1:

**Pull request merged**
