### PR TITLE
add .gitattributes - exclude tests, docs from archives

### PR DESCRIPTION
**Pull request by iamvar**
Just added .gitattributes to exclude tests, docs from archives

### CODE REVIEW

**Comment by iamvar** [comment]
> What purpose for this in deployer repo?

As I mentioned above - to exclude tests and docs from archives.
Will make releases a little smaller and will be faster downloaded with composer install

**Comment by antonmedv** [comment]
I think phar is better for Deployer =)

**Comment by iamvar** [comment]
Yes, but those who use it as composer dependency for the dev environment will get benefits from this change.
Tell me your concerns why you do not want to include it? I do not understand.

You can read about .gitattributes here https://php.watch/articles/composer-gitattributes

**Comment by iamvar** [comment]
Hello, so what do you think?
I do not see any negative effect from adding .gitattributes, but benefits for those who use deployer as composer dependency

**Comment by iamvar** [comment]
Hello, so what do you think?
I do not see any negative effect from adding .gitattributes, but benefits for those who use deployer as composer dependency

**Comment by Schrank** [comment]
Sounds to me likesomething useful. I use phar as well. But as long as the maintenance for "using deployer with composer" isn't killing us (this needs to be answered by @antonmedv), I think improving the experience is good.

**Pull request merged**
