### PR TITLE
Deployer Next 🚀

### PR DESCRIPTION
**Pull request by antonmedv**
In this PR you can see my current work on refactoring Deployer

* [x] main refactoring
* [x] upload/download
* [x] stage arg to task command
* [x] host ranges
* [x] src tests
* [x] recipe tests
* [x] refactor parallel
* [x] log file
* [x] command ssh to connect
* [x] `--roles` and `--hosts`
* [x] better config:dump
* [x] persistent collection

### CODE REVIEW

**Comment by staabm** [comment]
Thx for working in the next major version - great progress!

One nit: in case you welcome code review of this changes you should merge and create smaller PRs. At this size code reviews are very hard.

**Comment by antonmedv** [comment]
Code review doesn't necessary, thanks. You can see everything after merge, or now in the branch. You can comment or commits. 
Btw, I've reached 80% coverage.

**Comment by antonmedv** [comment]
Awesome stuff now can be done:

```php
host('[a:z].project.com')
    ->stage('production')
    ->set('deploy_path', '~/{{hostname}}');
```

Do rolling update in parallel (concurrency level = 10)
```
dep deploy production --parallel --limit 10
```

**Comment by antonmedv** [comment]
Deployer 5 will bring some useful stuff:
```php
    on(host('...'), function ($host) {
         run('...');
        // ...
        $host->set('value', '...');
    });
```
`on` func is experimental, but it can do some crazy stuff!

**Comment by reissr** [comment]
When is the next release? (I'm waiting for one of the commited fixes..) 😊

**Comment by antonmedv** [comment]
@reissr soon, i hope.

**Comment by antonmedv** [comment]
I'm so glad that I finally finished this thread! 🚀

**Comment by staabm** [comment]
🎉🎉

**Pull request merged**
