### PR TITLE
Add Minimum PHP Version to Composer File

### LINKED ISSUE #2538: require php in composer.json
I don't see "php" in composer.json, why is that ?

https://github.com/spatie/package-skeleton-php/blob/master/composer.json#L18

### PR DESCRIPTION
**Pull request by amayer5125**
Closes #2538

### CODE REVIEW

**Comment by Schrank** [comment]
Im nur sure we want to change composer api version? @amayer5125

**Comment by Schrank** [comment]
Wrong start, sorry, too early 🙈

thanks for the PR! 🥰

**Comment by antonmedv** [comment]
But it will duplicate php check. In composer and in bin/dep.

**Comment by amayer5125** [comment]
> Im not sure we want to change composer api version? @amayer5125

I added that without thinking about it. Probably should have brought it up in the PR. Composer 1.x [is being deprecated](https://blog.packagist.com/deprecating-composer-1-support/).

> But it will duplicate php check. In composer and in bin/dep

Should we remove the check in bin/dep or close this PR? In #2538 it seemed like you were saying we should add the php version back to the composer file.

**Comment by antonmedv** [comment]
I'm not sure. Let's don't rush. We have a few other types of installation: phar and dist. And both of them even more popular than composer. So we definitely need check in bin/dep. But what purpose of adding such check in composer?

**Comment by amayer5125** [comment]
Besides warning people when they are doing `composer require --dev deployer/deployer` that their php version isn't compatible I don't believe it does much else.

**Comment by antonmedv** [comment]
Question: is Deployer in the master branch truly supports 7.3?)

**Comment by amayer5125** [comment]
If I replace the named parameters in [tests/joy/recipe/named_arguments.php](https://github.com/deployphp/deployer/blob/master/tests/joy/recipe/named_arguments.php), all tests run green. Depending on the coverage of the tests, I would say that is a pretty good indicator that 7.3 is the minimum version.

**Comment by smknstd** [comment]
https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md

I think it would be good practice to change for something like :

```
"require": {
   "php": "^7.3|^8.0",
}
```

**Comment by smknstd** [comment]
@antonmedv the bin/dep check is also unbound. I think it should also check for upper bound. For example, v6 should warn it doesn't work on php8, don't you think ? https://github.com/deployphp/deployer/blob/6.x/bin/dep#L13

**Comment by antonmedv** [comment]
It will be cool to do. But it will require some effort on releasing. On v7 release process is automated.

**Review by kkrieger85 — APPROVED** [review]

**Review by Tobion — APPROVED** [review]

**Comment by Schrank** [comment]
@antonmedv I think if people want to install deployer via composer (which is a horrible idea) we should help them by telling them what PHP version to use :-)

If you tell me what to do, I'm happy to take care of it.

**Comment by antonmedv** [comment]
@Schrank it will be really cool.

**Comment by antonmedv** [comment]
Added.

**Pull request closed without merging**
