### PR TITLE
Added artisan:optimize command and automatically optimize Laravel deployments

### PR DESCRIPTION
**Pull request by garygreen**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

This will add a `artisan:optimize` command and also automatically optimize deployments. Laravel has an internal list of classes which the framework will add in one file to optimize performance - this is separate from composer's optimize autoloader.

### CODE REVIEW

**Comment by elfet** [comment]
Which laravel version?

**Comment by garygreen** [comment]
> Which laravel version?

Laravel has always had the optimize command.

**Comment by garygreen** [comment]
Suprisingly it's not very well documented, never has been but it's been there since 4.*. Here's the command as found in 5.1: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Foundation/Console/OptimizeCommand.php#L19

It's recommended to run this when you deploy as it makes a big difference for performance.

**Comment by pdbreen** [comment]
Just FYI - this has been a composer post install / post update script since at least v5.0 (didn't check earlier).  

https://github.com/laravel/laravel/blob/master/composer.json

So, explicit execution may not be needed and could actually cause issues if run after the symlink swap takes place.

**Comment by garygreen** [comment]
@pdbreen that's true, on second thoughts for default Laravel installs this PR isn't really needed.

**Pull request closed without merging**
