### PR TITLE
Make Deployer work with PHP 8.2

### PR DESCRIPTION
**Pull request by franmomu**
Replaces https://github.com/deployphp/deployer/pull/3401

Using @Konafets' work and updating the composer.lock file

Closes https://github.com/deployphp/deployer/issues/3399 and https://github.com/deployphp/deployer/pull/3401

- [x] Bug fix https://github.com/deployphp/deployer/issues/3399?

### CODE REVIEW

**Comment by B4rb4ross4** [comment]
Isn't the composer.lock ignored when composer is required by another package? I always thought so. And I don't think I misread the documentation (https://getcomposer.org/doc/02-libraries.md#lock-file). So your change should in theory have no effect.

**Comment by B4rb4ross4** [comment]
And the php 8.2 checks are missing
https://github.com/deployphp/deployer/blob/1f5cfb25c247506b8d2a12484c87f9b8b3fe3f9b/.github/workflows/test.yml#L14

**Comment by franmomu** [comment]
> Isn't the composer.lock ignored when a library is required by a project? I always thought so. And I don't think I misread the documentation (https://getcomposer.org/doc/02-libraries.md#lock-file). So your change should in theory have no effect.

The thing here, if I'm not wrong, is that this change would have effect in the next release because of this job: https://github.com/deployphp/deployer/blob/1f5cfb25c247506b8d2a12484c87f9b8b3fe3f9b/.github/workflows/release.yml

When a release is created, [it executes `bin/build`](https://github.com/deployphp/deployer/blob/1f5cfb25c247506b8d2a12484c87f9b8b3fe3f9b/.github/workflows/release.yml#L18) which [uses `composer install`](https://github.com/deployphp/deployer/blob/1f5cfb25c247506b8d2a12484c87f9b8b3fe3f9b/bin/build#L28) and generates the `dep` binary, then [the `composer.json` file is modified to remove some sections included the `require` one](https://github.com/deployphp/deployer/blob/1f5cfb25c247506b8d2a12484c87f9b8b3fe3f9b/.github/workflows/release.yml#L38-L59).

If you see https://packagist.org/packages/deployer/deployer#v7.0.2 there are no requirements there.

**Review by maxhelias — APPROVED** [review]

**Review by DamienHarper — APPROVED** [review]

**Review by Konafets — APPROVED** [review]

**Comment by UlrichThomasGabor** [comment]
@antonmedv Can you please release a new version with that PR merged?

**Comment by antonmedv** [comment]
Will try to do it today.

**Review by Jamesking56 — APPROVED** [review]

**Pull request merged**
