### PR TITLE
Upgrade PHPUnit

### PR DESCRIPTION
**Pull request by keradus**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

Brought to you by [PHP CS Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer)

### CODE REVIEW

**Comment by antonmedv** [comment]
Tests are falling.

**Comment by keradus** [comment]
Please, could you point where?
Travis is passing on all jobs.
Scrutinizer error is not on executing tests, but `TEST SETUP FAILED` with `There was an error (Event-ID 753253043b4b4c4fb114847fc77591c0)`. I cannot fix internal Scrutinizer issues ;)

**Comment by antonmedv** [comment]
Hmm, okay. I will check it myself.

**Comment by keradus** [comment]
ping @antonmedv

**Comment by antonmedv** [comment]
Why did you refactored phpdocs? :)

**Comment by keradus** [comment]
because creator of PHPUnit ask you to
https://thephp.cc/news/2016/02/questioning-phpunit-best-practices

**Pull request merged**
