### PR TITLE
Add statamic recipe

### PR DESCRIPTION
**Pull request by jonassiewertsen**
This PR does add a Statamic recipe with all Statamic specific commands needed for the deployment. 

I will remove the draft status, as soon as I did add some docs for the correct usage.
Is the 'How to' section in the docs the best place?

- [ ] Bug fix #…?
- [x] New feature?
- [ ] BC breaks?
- [ ] Deprecations?
- [ ] Tests added?
- [x] Changelog updated?

### CODE REVIEW

**Review by Schrank — APPROVED** [review]

**Comment by Schrank** [comment]
Never heard of it. Thanks for the contribution! 🥰

**Comment by jonassiewertsen** [comment]
Statamic is a great cms @Schrank, especially if you like Laravel 🚀

**Comment by jonassiewertsen** [comment]
The docs are in a different repo. I will add some documentation there soon!

**Comment by Schrank** [comment]
There is a german saying: "The farmer doesn't eat what he doesn't know" - therefore I don't eat laravel 😂 

But everything I hear about it sounds awesome, especially the eco system <3

**Comment by jonassiewertsen** [comment]
The community and ecosystem is great indeed :-)

**Comment by jackmcdade** [comment]
You should probably take a nibble at Laravel, but you should **definitely** eat Statamic. 3 Statamics a day keep the doctor away, or so I've heard.

**Review by lorisleiva — APPROVED** [review]

**Comment by Schrank** [comment]
@jonassiewertsen if you are happy with it now I'll merge it :-)

**Comment by jonassiewertsen** [comment]
We are ready to merge :-)

**Comment by Schrank** [comment]
So be it.

**Comment by Schrank** [comment]
Thanks for your work!

**Comment by jonassiewertsen** [comment]
Thanks for mergin :-)

**Pull request merged**
