### PR TITLE
[httpie] Delete unnecessary clone

### PR DESCRIPTION
**Pull request by joanhey**
- [ ] Bug fix #…?
- [ ] New feature?
- [ ] BC breaks?
- [ ] Tests added?
- [ ] Docs added?

      Please, regenerate docs by running next command:
      $ php bin/docgen

### CODE REVIEW

**Comment by antonmedv** [comment]
This is a big breaking change. Why?

**Comment by joanhey** [comment]
This change don't break anything. All works the same.

It is NOT necessary to clone this object.
We change directly the attributes in the received instance.

**Comment by joanhey** [comment]
When I have time I'll add tests to this class.
And it will be easier to make changes.

**Comment by antonmedv** [comment]
Clone is essential part. One can create a "boilerplate" and copy it via the method. Probably somebody relays on it already.

**Comment by joanhey** [comment]
But this is the contrary.
Clone it when you need it. And not httpie.

`return Httpie::get($url)->header(....)->send()
`
Here we don't needed.

`$response1 = Httpie::get($url)->header(....);`
Here is the same if it's cloned or not;

`$response2 = $response1->jsonBody(...);`
Here response2 is a copy of $reponse1, but like you said we changed $reponse1 too.

And the logical is that the developer use the clone if they want it. Not automatically Httpie.
```
$response2 = clone $response1;
$response2->jsonBody(....);
```

**Comment by joanhey** [comment]
But you are who will decide every PR we send you.

**Comment by joanhey** [comment]
Also it's possible to add a clone() method. And that will be semantically correct.

**Comment by joanhey** [comment]
A good example is the `fetch()` function
It's working without clone, but we can simplify the code, and use less instances.

Now:
```php
$http = $http->nothrow($nothrow);
foreach ($headers as $key => $value) {
        $http = $http->header($key, $value);
}
if ($body !== null) {
        $http = $http->body($body);
}
return $http->send($info);

```

After:
```php
$http->nothrow($nothrow);
foreach ($headers as $key => $value) {
        $http->header($key, $value);
}
if ($body !== null) {
        $http->body($body);
}
return $http->send($info);
```

**Comment by antonmedv** [comment]
Merged!

**Pull request closed without merging**
