### PR TITLE
Let user override phpunit locally.

### PR DESCRIPTION
**Pull request by lucasmichot**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

### CODE REVIEW

**Comment by antonmedv** [comment]
Why do you need it for?

**Comment by lucasmichot** [comment]
A person contributing might tweak phpunit.xml file for different reasons: tweaking the test file, setup coverage or whatever.

When running `vendor/bin/phpunit`, if `phpunit.xml` exists it will be taken into consideration. Or else `phpunit.xml.dist` will be used.

See https://phpunit.de/manual/current/en/organizing-tests.html

**Comment by antonmedv** [comment]
Why not tweak phpunit.xml itself then?

**Comment by lucasmichot** [comment]
Because, if a developer change it, it would be commited

**Comment by antonmedv** [comment]
> Because, if a developer change it, it would be commited

Don't `git add phpunit.xml` :)

**Comment by lucasmichot** [comment]
But does it is not obvious 
Have a look at `.gitignore` on https://github.com/symfony/symfony and https://github.com/laravel/framework

**Comment by antonmedv** [comment]
Okay, lets merge it.

**Pull request merged**
