### PR TITLE
ignore warning if tty is not writable

### PR DESCRIPTION
**Pull request by sweebee**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes 
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | #1713 

fixes running deployer on Gitlab CI.

### CODE REVIEW

**Comment by staabm** [comment]
are you sure the deployment will work when TTY doesn't work?

**Comment by sweebee** [comment]
Yes, at least for me it works on my local machine MacOS as docker in gitlab ci

**Comment by sweebee** [comment]
I've got this fix from dusk, which got the same problem.

https://github.com/laravel/dusk/pull/226/files

**Comment by antonmedv** [comment]
You should you config to set tty to off. Not ignore exception. 
Sorry but i can't accept this PR.

PS tty is needed only for known_hosts additions. And if you already pulled on server from github, it's in this list. (Or you can manually add hash to list or disable  SSH's known_hosts at all)

**Pull request closed without merging**
