### PR TITLE
dep init

### PR DESCRIPTION
**Pull request by elfet**
@deployphp/maintainer lets tests and discuss this :)

### CODE REVIEW

**Comment by elfet** [comment]
Pleas fix code style. @ZhukV #407

**Comment by ZhukV** [comment]
@elfet fixed

**Comment by elfet** [comment]
Cool! Can you write a doc about it feature?

**Comment by kbsali** [comment]
@ZhukV the maintainers seem to like it !!! It's only missing a little doc! ;)

**Comment by oanhnn** [comment]
Ping @elfet  @deployphp/maintainer

**Comment by elfet** [comment]
Lets merge! Docs will come late i hope).

**Pull request merged**
