### PR TITLE
Add option to set branch to deploy

### PR DESCRIPTION
**Pull request by osrecio**
| Q | A |
| --- | --- |
| Bug fix? | No |
| New feature? | Yes |
| BC breaks? | No |
| Deprecations? | No |
| Fixed tickets | N/A |

Add option --branch to set branch to deploy. Best way than get of env.

### CODE REVIEW

**Comment by pdbreen** [comment]
This looks like it would be a breaking change.  My server definitions set the branch via env.  While maybe not obvious at first, this makes perfect sense as I suspect many existing server definitions are environment specific (the documentation certainly guides people to use different server def for prod vs beta, etc).

**Comment by oanhnn** [comment]
Branch should be defined in environment variables and `--tag` option should be 
more preferred than `branch`.
If you want deploy on different branch, i think you should make more stages.

**Comment by elfet** [comment]
I like `--branch` options and i think we can add it in no BC.

**Comment by elfet** [comment]
Better to 4.x

**Comment by osrecio** [comment]
I agree wit you @pdbreen . I think the purpose is only add the option `--branch` without delete env('branch'). But If you make `dep deploy --branch=x` wins over env=branch of server because you can decide in deploy what branch you want deploy IMHO.

**Comment by osrecio** [comment]
Ok I will don't change my PR beacuse @oanhnn make a PR with correct code of my point of view: https://github.com/deployphp/deployer/pull/771 

Thanks!

**Comment by elfet** [comment]
Done in v4.

**Pull request closed without merging**
