### PR TITLE
DD#0000: feat: Move var-exporter into main requirements

### LINKED ISSUE #3652: Magento 2 - Outdated generated code
- Deployer version: 7.3.1
- Deployment OS: Ubuntu 18.04

For us it often happens that the files in `generated/code` are outdated. It seems like these are generated on basis of the release before.

Is this a known issue? Is there any reason why https://deployer.org/docs/7.x/recipe/magento2#magentoset_cache_prefix is only part of the artifact deployment?

### PR DESCRIPTION
**Pull request by valguss**
- [ ] Bug fix #3652 moves var-exporter from dev-requirments to requirements
- [ ] New feature?
- [ ] BC breaks?
- [ ] Tests added?
- [ ] Docs added?

      Please, regenerate docs by running next command:
      $ php bin/docgen

### CODE REVIEW

**Comment by antonmedv** [comment]
Can we do this without var-exporter?

**Comment by valguss** [comment]
Think I was asked to use it. Will update to remove now

**Comment by valguss** [comment]
Updated to var_export

**Comment by torhoehn** [comment]
@valguss Could you please resolve the conflicts here to get it merged?

**Comment by valguss** [comment]
Always useful.

**Review by antonmedv — APPROVED** [review]

**Pull request merged**
