### PR TITLE
Change writable dirs of sulu recipe to include all shared dirs.

### PR DESCRIPTION
**Pull request by AndreasA**
- [X] Bug fix #...? 
#3386
- [X] New feature? No
- [X] BC breaks? No
- [X] Tests added? Not needed.
- [X] Docs added? Not needed.

### CODE REVIEW

**Review by alexander-schranz — APPROVED** [review]
Sulu Core Team Member here. This change looks required as the update from Deployer 6 to 7 the Symfony `var` directory is not longer `writable_recursive` `true` like already reported in #3379. The other directories need also be set to be writable.

Alternative would be that the `symfony.php` recipe sets:

```php
set('writeable_dirs', ['var']);
set('writable_recursive', true);
```

Which would maybe something somebody would expect for a directory called `var`. But I think there was maybe a specific reasons not longer use `writable_recursive` by default @antonmedv?

**Comment by antonmedv** [comment]
Can we add this to sulu recipe?

    add('writeable_dirs', ['var']);

**Comment by AndreasA** [comment]
@antonmedv without `writable_recursive` set to `true` it will not make the other dirs in `var` writable. `var` is already part of the Symfony recipe, that is the base for this recipe.

**Comment by alexander-schranz** [comment]
> Can we add this to sulu recipe?
> add('writeable_dirs', ['var']);

The `var` directory is already there as `sulu.php` uses the `symfony.php` recipe. The problem I think is mostly that somebody is copying things from another servers into the symfony applications `var` directory. And in deployer 6 with `writable_recursive` set to `true` you never run into any problems with this kind of sync processes as `writable_recursive` did follow symlinks to the shared dirs. And in deployer 7 with `writable_recursive` set to `false` we need to add all `shared_dirs` which are writeable again on `writeable_dirs`. Or as alternative add `writable_recursive` `true` again to `symfony.php` then all symfony depending recipes don't need again add all shared_dirs which are writeable again to writeable_dirs.

Hope that was not to confusing 🙈

**Comment by antonmedv** [comment]
Let's use writable_recursive.

**Comment by antonmedv** [comment]
Let's create a PR.

**Comment by AndreasA** [comment]
@antonmedv done: https://github.com/deployphp/deployer/pull/3451

**Pull request closed without merging**
