### PR TITLE
Switch to PSR-2

### PR DESCRIPTION
**Pull request by lucasmichot**
- Updated reamde
- Added an editoconfig file and php_cs file
- formatted code - very few code changes (mainly spaces and blank lines)

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by lucasmichot** [comment]
When it's about PSR, @GrahamCampbell is never very far :-)

**Comment by GrahamCampbell** [comment]
lol

**Comment by GrahamCampbell** [comment]
@elfet How about you guys enable [StyleCI](https://styleci.io/) on this repo to make sure you stay PSR-2 compient and contributors get noticed via github's status API on their PRs if they're not following the coding style guide you've defied.

**Comment by ZeeCoder** [comment]
:+1: Editorconfig ftw

**Comment by lucasmichot** [comment]
For a reason Travis failed but this seems related to something else : https://travis-ci.org/deployphp/deployer/jobs/67236631#L97

**Comment by elfet** [comment]
So cool!

**Comment by elfet** [comment]
@GrahamCampbell got 500 error on styleCI =)

**Comment by lucasmichot** [comment]
The config file was probably missing @elfet 
See https://github.com/deployphp/deployer/pull/362

**Comment by ZeeCoder** [comment]
I tried this myself, and I got 500 error too.
There's a default setup though, so having the config file should not be mandatory, it shouldn't cause a 500 error.

For me the solution was, to first visit the "account" page, where I could enable the service for one of my repos, and after I got at least one, the /repo page rendered properly.

That aside, I also think we should add the `.styleci.yml` file added in #362.

**Pull request merged**
