### PR TITLE
Rename runLocally and localServer

### PR DESCRIPTION
**Pull request by elfet**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes
| BC breaks?    | Yes
| Deprecations? | Yes
| Fixed tickets | N/A

What about renaming `runLocally` and `localServer` to new, more consistent functions as `local/run` and `local/server`?

### CODE REVIEW

**Comment by elfet** [comment]
Pool https://twitter.com/antonmedv/status/817261784612511746
image

**Comment by elfet** [comment]
Well, i think to use `local\run`. 🙄

**Comment by mbrodala** [comment]
Now that #942 was merged can you move that function to `local\test`, too? I'd do it but it's your PR. ;-)

**Comment by elfet** [comment]
Moved.

**Comment by elfet** [comment]
Btw, i'm still thinking. Maybe it's better so stick with more simple runLocally, then fancy local\run.

**Comment by elfet** [comment]
After a lot of thinking i came with idea what BC is bad and there is nothing wrong with current naming. So i'm closing this PR.

**Pull request closed without merging**
