### PR TITLE
added onStart and onEnd tasks

### PR DESCRIPTION
**Pull request by radutopala**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | Yes
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | #791 

A quick fix for added on start and on end tasks, similar to beforeAll / afterAll from #791.

@elfet pls close this PR if you have a better way soon. Thanks!

### CODE REVIEW

**Comment by elfet** [comment]
I think this is not solution for #791. Now working of this by myself. But need more time.

**Comment by radutopala** [comment]
I needed a fast solution to a problem I have here, but happy to use yours when it's done.

**Comment by radutopala** [comment]
@antonmedv was this issue addressed in any of the newer versions of deployer?

**Comment by antonmedv** [comment]
Actually we are using simple before/after as this has same api. 

Main idea here is to try to keep deployer simple, and allow user to do anything inside deploy.php

**Pull request closed without merging**
