### PR TITLE
CN-411 Fix exit code for parallel execution

### PR DESCRIPTION
**Pull request by aheart**
| Q             | A
| ------------- | ---
| Bug fix?      | Yes
| New feature?  | No
| BC breaks?    |  No
| Deprecations? | No
| Fixed tickets | N/A

Backporting fix from 4.0
See https://github.com/deployphp/deployer/commit/3e40fcd958e2ac6eeb292fe1911f652803fe50db#diff-ecc506bcfd58cb6526cd2db33d5121cdR195

### CODE REVIEW

**Comment by elfet** [comment]
Why you just can upgrade to 4.0 version?

**Comment by aheart** [comment]
One of our build servers is stuck with PHP 5.4 and will stay that way for an unknown period of time.
Everyone who is in a similar position could benefit from this, but If you would rather not invest time into 3.x I completely understand.
We can use our fork until an upgrade to 4.x is possible.

Thank you for taking the time to review this PR.

**Comment by elfet** [comment]
@aheart can you use it via composer installation?

**Comment by aheart** [comment]
@elfet No, but I've created a phar using your build script. Works well, thank you.

**Pull request merged**
