### PR TITLE
Check (shared) file exists

### PR DESCRIPTION
**Pull request by dsmink**
Doing a check if the shared file already exists.
A touch could result in a 'Permission denied' causing the deploy to stop.

### CODE REVIEW

**Comment by antonmedv** [comment]
I think in this case deploy should stop?

**Comment by dsmink** [comment]
@antonmedv
Why? The shared file does not have to be writable by the person (or its group) performing the deploy is it? This is the case in our situation. Also, touching a file that already exists only changes the modification time. That is where our deploy fails now.

**Comment by antonmedv** [comment]
Got it.

**Review by Schrank — APPROVED** [review]

**Comment by Schrank** [comment]
@antonmedv do you want/need anything to merge this? A test or something?

**Comment by antonmedv** [comment]
Nice! Thanks for pr and merge hustle.

**Pull request merged**
