### PR TITLE
Add Symfony 5 support #SymfonyHackday

### PR DESCRIPTION
**Pull request by patrick-mota**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | No
| BC breaks?    | No
| Deprecations? | No
| Fixed tickets | N/A

Add Symfony 5 Support
#SymfonyHackday

### CODE REVIEW

**Comment by patrick-mota** [comment]
Sorry I have some issues running in my localhost phpunit, I'm fixing the errors from travis.

**Comment by patrick-mota** [comment]
Should be fine, don't hesitate if I have to modify something, thank you.

**Comment by danielchodusov** [comment]
@antonmedv Hi Anton, would you be please so kind and merge this? So we can use deployer with Symfony 5? Thank you.

**Comment by akondas** [comment]
Hi @antonmedv, Is there anything else we need to do here?

**Comment by antonmedv** [comment]
We will release on weekends! 

Note what you can always use dist version: `deployer/dist`.

**Comment by akondas** [comment]
Thanks.

**Comment by helhum** [comment]
This introduces a regression, as at least the [SSH Client](https://github.com/deployphp/deployer/blob/97c63e91cce93fb46b921de9908f69c7bcbebd32/src/Ssh/Client.php#L149) isn't compatible with symfony/process 5.x

Error message:

```
[TypeError] Argument 1 passed to                                               
             Symfony\Component\Process\Process::__construct() must be of the    
             type array, string given, called in                                
             /root/.composer/vendor/deployer/deployer/src/Ssh/Client.php on line
             149                                                                
```

**Comment by YetiCGN** [comment]
@helhum Yup, I've noticed the same problem. There is also an issue for this already: https://github.com/deployphp/deployer/issues/1972

**Pull request merged**
