### PR TITLE
Update symfony package dependencies to 4.0

### PR DESCRIPTION
**Pull request by xakzona**
| Q             | A
| ------------- | ---
| Bug fix?      | No
| New feature?  | No
| BC breaks?    | No
| Deprecations? | Yes
| Fixed tickets | N/A

### CODE REVIEW

**Comment by solofeed** [comment]
Merge please as soon as possible)

**Comment by Pavlentiycomua** [comment]
Waiting for merge too

**Comment by dron-alterpost** [comment]
I'm not waiting for Santa Claus like for this PR. Merge this please.

**Comment by Amicus93** [comment]
Merge this PR please

**Comment by antonmedv** [comment]
Guys! Will try to find time as soon as possible! 

While waiting for this consider buying me a beer 🍺 paypal.me/antonmedv

**Comment by solofeed** [comment]
@antonmedv Can you create a tag for latest update?

**Comment by itelmenko** [comment]
Yes, please, add a tag, @antonmedv

**Pull request merged**
